// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.2
// source: proto/rpg_class/rpg_class.proto

package rpg_class

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RPGClassService_CreateRPGClass_FullMethodName          = "/rpg_class.RPGClassService/CreateRPGClass"
	RPGClassService_GetRPGClass_FullMethodName             = "/rpg_class.RPGClassService/GetRPGClass"
	RPGClassService_UpdateRPGClass_FullMethodName          = "/rpg_class.RPGClassService/UpdateRPGClass"
	RPGClassService_ListRPGClasses_FullMethodName          = "/rpg_class.RPGClassService/ListRPGClasses"
	RPGClassService_DeleteRPGClass_FullMethodName          = "/rpg_class.RPGClassService/DeleteRPGClass"
	RPGClassService_AddSkillToRPGClass_FullMethodName      = "/rpg_class.RPGClassService/AddSkillToRPGClass"
	RPGClassService_RemoveSkillFromRPGClass_FullMethodName = "/rpg_class.RPGClassService/RemoveSkillFromRPGClass"
	RPGClassService_ListRPGClassSkills_FullMethodName      = "/rpg_class.RPGClassService/ListRPGClassSkills"
)

// RPGClassServiceClient is the client API for RPGClassService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RPGClassServiceClient interface {
	// CreateRPGClass creates a new RPG class
	CreateRPGClass(ctx context.Context, in *CreateRPGClassRequest, opts ...grpc.CallOption) (*CreateRPGClassResponse, error)
	// GetRPGClass retrieves an RPG class by ID
	GetRPGClass(ctx context.Context, in *GetRPGClassRequest, opts ...grpc.CallOption) (*GetRPGClassResponse, error)
	// UpdateRPGClass updates an existing RPG class
	UpdateRPGClass(ctx context.Context, in *UpdateRPGClassRequest, opts ...grpc.CallOption) (*UpdateRPGClassResponse, error)
	// ListRPGClasses lists RPG classes for an RPG system with pagination
	ListRPGClasses(ctx context.Context, in *ListRPGClassesRequest, opts ...grpc.CallOption) (*ListRPGClassesResponse, error)
	// DeleteRPGClass deletes an RPG class
	DeleteRPGClass(ctx context.Context, in *DeleteRPGClassRequest, opts ...grpc.CallOption) (*DeleteRPGClassResponse, error)
	// AddSkillToRPGClass adds a skill to an RPG class
	AddSkillToRPGClass(ctx context.Context, in *AddSkillToRPGClassRequest, opts ...grpc.CallOption) (*AddSkillToRPGClassResponse, error)
	// RemoveSkillFromRPGClass removes a skill from an RPG class
	RemoveSkillFromRPGClass(ctx context.Context, in *RemoveSkillFromRPGClassRequest, opts ...grpc.CallOption) (*RemoveSkillFromRPGClassResponse, error)
	// ListRPGClassSkills lists skills for an RPG class
	ListRPGClassSkills(ctx context.Context, in *ListRPGClassSkillsRequest, opts ...grpc.CallOption) (*ListRPGClassSkillsResponse, error)
}

type rPGClassServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRPGClassServiceClient(cc grpc.ClientConnInterface) RPGClassServiceClient {
	return &rPGClassServiceClient{cc}
}

func (c *rPGClassServiceClient) CreateRPGClass(ctx context.Context, in *CreateRPGClassRequest, opts ...grpc.CallOption) (*CreateRPGClassResponse, error) {
	out := new(CreateRPGClassResponse)
	err := c.cc.Invoke(ctx, RPGClassService_CreateRPGClass_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPGClassServiceClient) GetRPGClass(ctx context.Context, in *GetRPGClassRequest, opts ...grpc.CallOption) (*GetRPGClassResponse, error) {
	out := new(GetRPGClassResponse)
	err := c.cc.Invoke(ctx, RPGClassService_GetRPGClass_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPGClassServiceClient) UpdateRPGClass(ctx context.Context, in *UpdateRPGClassRequest, opts ...grpc.CallOption) (*UpdateRPGClassResponse, error) {
	out := new(UpdateRPGClassResponse)
	err := c.cc.Invoke(ctx, RPGClassService_UpdateRPGClass_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPGClassServiceClient) ListRPGClasses(ctx context.Context, in *ListRPGClassesRequest, opts ...grpc.CallOption) (*ListRPGClassesResponse, error) {
	out := new(ListRPGClassesResponse)
	err := c.cc.Invoke(ctx, RPGClassService_ListRPGClasses_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPGClassServiceClient) DeleteRPGClass(ctx context.Context, in *DeleteRPGClassRequest, opts ...grpc.CallOption) (*DeleteRPGClassResponse, error) {
	out := new(DeleteRPGClassResponse)
	err := c.cc.Invoke(ctx, RPGClassService_DeleteRPGClass_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPGClassServiceClient) AddSkillToRPGClass(ctx context.Context, in *AddSkillToRPGClassRequest, opts ...grpc.CallOption) (*AddSkillToRPGClassResponse, error) {
	out := new(AddSkillToRPGClassResponse)
	err := c.cc.Invoke(ctx, RPGClassService_AddSkillToRPGClass_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPGClassServiceClient) RemoveSkillFromRPGClass(ctx context.Context, in *RemoveSkillFromRPGClassRequest, opts ...grpc.CallOption) (*RemoveSkillFromRPGClassResponse, error) {
	out := new(RemoveSkillFromRPGClassResponse)
	err := c.cc.Invoke(ctx, RPGClassService_RemoveSkillFromRPGClass_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPGClassServiceClient) ListRPGClassSkills(ctx context.Context, in *ListRPGClassSkillsRequest, opts ...grpc.CallOption) (*ListRPGClassSkillsResponse, error) {
	out := new(ListRPGClassSkillsResponse)
	err := c.cc.Invoke(ctx, RPGClassService_ListRPGClassSkills_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPGClassServiceServer is the server API for RPGClassService service.
// All implementations must embed UnimplementedRPGClassServiceServer
// for forward compatibility
type RPGClassServiceServer interface {
	// CreateRPGClass creates a new RPG class
	CreateRPGClass(context.Context, *CreateRPGClassRequest) (*CreateRPGClassResponse, error)
	// GetRPGClass retrieves an RPG class by ID
	GetRPGClass(context.Context, *GetRPGClassRequest) (*GetRPGClassResponse, error)
	// UpdateRPGClass updates an existing RPG class
	UpdateRPGClass(context.Context, *UpdateRPGClassRequest) (*UpdateRPGClassResponse, error)
	// ListRPGClasses lists RPG classes for an RPG system with pagination
	ListRPGClasses(context.Context, *ListRPGClassesRequest) (*ListRPGClassesResponse, error)
	// DeleteRPGClass deletes an RPG class
	DeleteRPGClass(context.Context, *DeleteRPGClassRequest) (*DeleteRPGClassResponse, error)
	// AddSkillToRPGClass adds a skill to an RPG class
	AddSkillToRPGClass(context.Context, *AddSkillToRPGClassRequest) (*AddSkillToRPGClassResponse, error)
	// RemoveSkillFromRPGClass removes a skill from an RPG class
	RemoveSkillFromRPGClass(context.Context, *RemoveSkillFromRPGClassRequest) (*RemoveSkillFromRPGClassResponse, error)
	// ListRPGClassSkills lists skills for an RPG class
	ListRPGClassSkills(context.Context, *ListRPGClassSkillsRequest) (*ListRPGClassSkillsResponse, error)
	mustEmbedUnimplementedRPGClassServiceServer()
}

// UnimplementedRPGClassServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRPGClassServiceServer struct {
}

func (UnimplementedRPGClassServiceServer) CreateRPGClass(context.Context, *CreateRPGClassRequest) (*CreateRPGClassResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRPGClass not implemented")
}
func (UnimplementedRPGClassServiceServer) GetRPGClass(context.Context, *GetRPGClassRequest) (*GetRPGClassResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRPGClass not implemented")
}
func (UnimplementedRPGClassServiceServer) UpdateRPGClass(context.Context, *UpdateRPGClassRequest) (*UpdateRPGClassResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRPGClass not implemented")
}
func (UnimplementedRPGClassServiceServer) ListRPGClasses(context.Context, *ListRPGClassesRequest) (*ListRPGClassesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRPGClasses not implemented")
}
func (UnimplementedRPGClassServiceServer) DeleteRPGClass(context.Context, *DeleteRPGClassRequest) (*DeleteRPGClassResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRPGClass not implemented")
}
func (UnimplementedRPGClassServiceServer) AddSkillToRPGClass(context.Context, *AddSkillToRPGClassRequest) (*AddSkillToRPGClassResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSkillToRPGClass not implemented")
}
func (UnimplementedRPGClassServiceServer) RemoveSkillFromRPGClass(context.Context, *RemoveSkillFromRPGClassRequest) (*RemoveSkillFromRPGClassResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveSkillFromRPGClass not implemented")
}
func (UnimplementedRPGClassServiceServer) ListRPGClassSkills(context.Context, *ListRPGClassSkillsRequest) (*ListRPGClassSkillsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRPGClassSkills not implemented")
}
func (UnimplementedRPGClassServiceServer) mustEmbedUnimplementedRPGClassServiceServer() {}

// UnsafeRPGClassServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RPGClassServiceServer will
// result in compilation errors.
type UnsafeRPGClassServiceServer interface {
	mustEmbedUnimplementedRPGClassServiceServer()
}

func RegisterRPGClassServiceServer(s grpc.ServiceRegistrar, srv RPGClassServiceServer) {
	s.RegisterService(&RPGClassService_ServiceDesc, srv)
}

func _RPGClassService_CreateRPGClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRPGClassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPGClassServiceServer).CreateRPGClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPGClassService_CreateRPGClass_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPGClassServiceServer).CreateRPGClass(ctx, req.(*CreateRPGClassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPGClassService_GetRPGClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRPGClassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPGClassServiceServer).GetRPGClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPGClassService_GetRPGClass_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPGClassServiceServer).GetRPGClass(ctx, req.(*GetRPGClassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPGClassService_UpdateRPGClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRPGClassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPGClassServiceServer).UpdateRPGClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPGClassService_UpdateRPGClass_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPGClassServiceServer).UpdateRPGClass(ctx, req.(*UpdateRPGClassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPGClassService_ListRPGClasses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRPGClassesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPGClassServiceServer).ListRPGClasses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPGClassService_ListRPGClasses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPGClassServiceServer).ListRPGClasses(ctx, req.(*ListRPGClassesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPGClassService_DeleteRPGClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRPGClassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPGClassServiceServer).DeleteRPGClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPGClassService_DeleteRPGClass_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPGClassServiceServer).DeleteRPGClass(ctx, req.(*DeleteRPGClassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPGClassService_AddSkillToRPGClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSkillToRPGClassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPGClassServiceServer).AddSkillToRPGClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPGClassService_AddSkillToRPGClass_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPGClassServiceServer).AddSkillToRPGClass(ctx, req.(*AddSkillToRPGClassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPGClassService_RemoveSkillFromRPGClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSkillFromRPGClassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPGClassServiceServer).RemoveSkillFromRPGClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPGClassService_RemoveSkillFromRPGClass_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPGClassServiceServer).RemoveSkillFromRPGClass(ctx, req.(*RemoveSkillFromRPGClassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPGClassService_ListRPGClassSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRPGClassSkillsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPGClassServiceServer).ListRPGClassSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPGClassService_ListRPGClassSkills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPGClassServiceServer).ListRPGClassSkills(ctx, req.(*ListRPGClassSkillsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RPGClassService_ServiceDesc is the grpc.ServiceDesc for RPGClassService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RPGClassService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpg_class.RPGClassService",
	HandlerType: (*RPGClassServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRPGClass",
			Handler:    _RPGClassService_CreateRPGClass_Handler,
		},
		{
			MethodName: "GetRPGClass",
			Handler:    _RPGClassService_GetRPGClass_Handler,
		},
		{
			MethodName: "UpdateRPGClass",
			Handler:    _RPGClassService_UpdateRPGClass_Handler,
		},
		{
			MethodName: "ListRPGClasses",
			Handler:    _RPGClassService_ListRPGClasses_Handler,
		},
		{
			MethodName: "DeleteRPGClass",
			Handler:    _RPGClassService_DeleteRPGClass_Handler,
		},
		{
			MethodName: "AddSkillToRPGClass",
			Handler:    _RPGClassService_AddSkillToRPGClass_Handler,
		},
		{
			MethodName: "RemoveSkillFromRPGClass",
			Handler:    _RPGClassService_RemoveSkillFromRPGClass_Handler,
		},
		{
			MethodName: "ListRPGClassSkills",
			Handler:    _RPGClassService_ListRPGClassSkills_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/rpg_class/rpg_class.proto",
}
