// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/story/story.proto

package story

import (
	common "github.com/story-engine/main-service/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Story represents a story entity with versioning
type Story struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId        string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Title           string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Status          string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	VersionNumber   int32                  `protobuf:"varint,5,opt,name=version_number,json=versionNumber,proto3" json:"version_number,omitempty"`
	RootStoryId     string                 `protobuf:"bytes,6,opt,name=root_story_id,json=rootStoryId,proto3" json:"root_story_id,omitempty"`
	PreviousStoryId string                 `protobuf:"bytes,7,opt,name=previous_story_id,json=previousStoryId,proto3" json:"previous_story_id,omitempty"` // optional
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Story) Reset() {
	*x = Story{}
	mi := &file_proto_story_story_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Story) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Story) ProtoMessage() {}

func (x *Story) ProtoReflect() protoreflect.Message {
	mi := &file_proto_story_story_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Story.ProtoReflect.Descriptor instead.
func (*Story) Descriptor() ([]byte, []int) {
	return file_proto_story_story_proto_rawDescGZIP(), []int{0}
}

func (x *Story) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Story) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Story) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Story) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Story) GetVersionNumber() int32 {
	if x != nil {
		return x.VersionNumber
	}
	return 0
}

func (x *Story) GetRootStoryId() string {
	if x != nil {
		return x.RootStoryId
	}
	return ""
}

func (x *Story) GetPreviousStoryId() string {
	if x != nil {
		return x.PreviousStoryId
	}
	return ""
}

func (x *Story) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Story) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Chapter represents a chapter in a story
type Chapter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StoryId       string                 `protobuf:"bytes,2,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	Number        int32                  `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chapter) Reset() {
	*x = Chapter{}
	mi := &file_proto_story_story_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chapter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chapter) ProtoMessage() {}

func (x *Chapter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_story_story_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chapter.ProtoReflect.Descriptor instead.
func (*Chapter) Descriptor() ([]byte, []int) {
	return file_proto_story_story_proto_rawDescGZIP(), []int{1}
}

func (x *Chapter) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Chapter) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

func (x *Chapter) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Chapter) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Chapter) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Chapter) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Chapter) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Scene represents a scene in a chapter
type Scene struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StoryId        string                 `protobuf:"bytes,2,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	ChapterId      string                 `protobuf:"bytes,3,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	OrderNum       int32                  `protobuf:"varint,4,opt,name=order_num,json=orderNum,proto3" json:"order_num,omitempty"`
	Goal           string                 `protobuf:"bytes,5,opt,name=goal,proto3" json:"goal,omitempty"`
	TimeRef        string                 `protobuf:"bytes,6,opt,name=time_ref,json=timeRef,proto3" json:"time_ref,omitempty"`
	PovCharacterId string                 `protobuf:"bytes,7,opt,name=pov_character_id,json=povCharacterId,proto3" json:"pov_character_id,omitempty"` // optional
	LocationId     string                 `protobuf:"bytes,8,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`               // optional
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Scene) Reset() {
	*x = Scene{}
	mi := &file_proto_story_story_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scene) ProtoMessage() {}

func (x *Scene) ProtoReflect() protoreflect.Message {
	mi := &file_proto_story_story_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scene.ProtoReflect.Descriptor instead.
func (*Scene) Descriptor() ([]byte, []int) {
	return file_proto_story_story_proto_rawDescGZIP(), []int{2}
}

func (x *Scene) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Scene) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

func (x *Scene) GetChapterId() string {
	if x != nil {
		return x.ChapterId
	}
	return ""
}

func (x *Scene) GetOrderNum() int32 {
	if x != nil {
		return x.OrderNum
	}
	return 0
}

func (x *Scene) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *Scene) GetTimeRef() string {
	if x != nil {
		return x.TimeRef
	}
	return ""
}

func (x *Scene) GetPovCharacterId() string {
	if x != nil {
		return x.PovCharacterId
	}
	return ""
}

func (x *Scene) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *Scene) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Scene) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateStoryRequest is the request to create a new story
type CreateStoryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenantId        string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // optional if provided in metadata
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CreatedByUserId string                 `protobuf:"bytes,3,opt,name=created_by_user_id,json=createdByUserId,proto3" json:"created_by_user_id,omitempty"` // optional
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateStoryRequest) Reset() {
	*x = CreateStoryRequest{}
	mi := &file_proto_story_story_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStoryRequest) ProtoMessage() {}

func (x *CreateStoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_story_story_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStoryRequest.ProtoReflect.Descriptor instead.
func (*CreateStoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_story_story_proto_rawDescGZIP(), []int{3}
}

func (x *CreateStoryRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateStoryRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateStoryRequest) GetCreatedByUserId() string {
	if x != nil {
		return x.CreatedByUserId
	}
	return ""
}

// CreateStoryResponse is the response after creating a story
type CreateStoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Story         *Story                 `protobuf:"bytes,1,opt,name=story,proto3" json:"story,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStoryResponse) Reset() {
	*x = CreateStoryResponse{}
	mi := &file_proto_story_story_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStoryResponse) ProtoMessage() {}

func (x *CreateStoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_story_story_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStoryResponse.ProtoReflect.Descriptor instead.
func (*CreateStoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_story_story_proto_rawDescGZIP(), []int{4}
}

func (x *CreateStoryResponse) GetStory() *Story {
	if x != nil {
		return x.Story
	}
	return nil
}

// GetStoryRequest is the request to get a story by ID
type GetStoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoryRequest) Reset() {
	*x = GetStoryRequest{}
	mi := &file_proto_story_story_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoryRequest) ProtoMessage() {}

func (x *GetStoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_story_story_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoryRequest.ProtoReflect.Descriptor instead.
func (*GetStoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_story_story_proto_rawDescGZIP(), []int{5}
}

func (x *GetStoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetStoryResponse is the response containing a story
type GetStoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Story         *Story                 `protobuf:"bytes,1,opt,name=story,proto3" json:"story,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoryResponse) Reset() {
	*x = GetStoryResponse{}
	mi := &file_proto_story_story_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoryResponse) ProtoMessage() {}

func (x *GetStoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_story_story_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoryResponse.ProtoReflect.Descriptor instead.
func (*GetStoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_story_story_proto_rawDescGZIP(), []int{6}
}

func (x *GetStoryResponse) GetStory() *Story {
	if x != nil {
		return x.Story
	}
	return nil
}

// ListStoriesRequest is the request to list stories for a tenant
type ListStoriesRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	TenantId      string                    `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // optional if provided in metadata
	Pagination    *common.PaginationRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStoriesRequest) Reset() {
	*x = ListStoriesRequest{}
	mi := &file_proto_story_story_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStoriesRequest) ProtoMessage() {}

func (x *ListStoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_story_story_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStoriesRequest.ProtoReflect.Descriptor instead.
func (*ListStoriesRequest) Descriptor() ([]byte, []int) {
	return file_proto_story_story_proto_rawDescGZIP(), []int{7}
}

func (x *ListStoriesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListStoriesRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// ListStoriesResponse is the response containing a list of stories
type ListStoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stories       []*Story               `protobuf:"bytes,1,rep,name=stories,proto3" json:"stories,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStoriesResponse) Reset() {
	*x = ListStoriesResponse{}
	mi := &file_proto_story_story_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStoriesResponse) ProtoMessage() {}

func (x *ListStoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_story_story_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStoriesResponse.ProtoReflect.Descriptor instead.
func (*ListStoriesResponse) Descriptor() ([]byte, []int) {
	return file_proto_story_story_proto_rawDescGZIP(), []int{8}
}

func (x *ListStoriesResponse) GetStories() []*Story {
	if x != nil {
		return x.Stories
	}
	return nil
}

func (x *ListStoriesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// CloneStoryRequest is the request to clone a story
type CloneStoryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SourceStoryId   string                 `protobuf:"bytes,1,opt,name=source_story_id,json=sourceStoryId,proto3" json:"source_story_id,omitempty"`
	CreatedByUserId string                 `protobuf:"bytes,2,opt,name=created_by_user_id,json=createdByUserId,proto3" json:"created_by_user_id,omitempty"` // optional
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CloneStoryRequest) Reset() {
	*x = CloneStoryRequest{}
	mi := &file_proto_story_story_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneStoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneStoryRequest) ProtoMessage() {}

func (x *CloneStoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_story_story_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneStoryRequest.ProtoReflect.Descriptor instead.
func (*CloneStoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_story_story_proto_rawDescGZIP(), []int{9}
}

func (x *CloneStoryRequest) GetSourceStoryId() string {
	if x != nil {
		return x.SourceStoryId
	}
	return ""
}

func (x *CloneStoryRequest) GetCreatedByUserId() string {
	if x != nil {
		return x.CreatedByUserId
	}
	return ""
}

// CloneStoryResponse is the response after cloning a story
type CloneStoryResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Story            *Story                 `protobuf:"bytes,1,opt,name=story,proto3" json:"story,omitempty"`
	NewVersionNumber int32                  `protobuf:"varint,2,opt,name=new_version_number,json=newVersionNumber,proto3" json:"new_version_number,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CloneStoryResponse) Reset() {
	*x = CloneStoryResponse{}
	mi := &file_proto_story_story_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneStoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneStoryResponse) ProtoMessage() {}

func (x *CloneStoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_story_story_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneStoryResponse.ProtoReflect.Descriptor instead.
func (*CloneStoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_story_story_proto_rawDescGZIP(), []int{10}
}

func (x *CloneStoryResponse) GetStory() *Story {
	if x != nil {
		return x.Story
	}
	return nil
}

func (x *CloneStoryResponse) GetNewVersionNumber() int32 {
	if x != nil {
		return x.NewVersionNumber
	}
	return 0
}

// ListStoryVersionsRequest is the request to list all versions of a story
type ListStoryVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootStoryId   string                 `protobuf:"bytes,1,opt,name=root_story_id,json=rootStoryId,proto3" json:"root_story_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStoryVersionsRequest) Reset() {
	*x = ListStoryVersionsRequest{}
	mi := &file_proto_story_story_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStoryVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStoryVersionsRequest) ProtoMessage() {}

func (x *ListStoryVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_story_story_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStoryVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListStoryVersionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_story_story_proto_rawDescGZIP(), []int{11}
}

func (x *ListStoryVersionsRequest) GetRootStoryId() string {
	if x != nil {
		return x.RootStoryId
	}
	return ""
}

// ListStoryVersionsResponse is the response containing all versions
type ListStoryVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*Story               `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStoryVersionsResponse) Reset() {
	*x = ListStoryVersionsResponse{}
	mi := &file_proto_story_story_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStoryVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStoryVersionsResponse) ProtoMessage() {}

func (x *ListStoryVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_story_story_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStoryVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListStoryVersionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_story_story_proto_rawDescGZIP(), []int{12}
}

func (x *ListStoryVersionsResponse) GetVersions() []*Story {
	if x != nil {
		return x.Versions
	}
	return nil
}

var File_proto_story_story_proto protoreflect.FileDescriptor

const file_proto_story_story_proto_rawDesc = "" +
	"\n" +
	"\x17proto/story/story.proto\x12\x05story\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19proto/common/common.proto\"\xcf\x02\n" +
	"\x05Story\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12%\n" +
	"\x0eversion_number\x18\x05 \x01(\x05R\rversionNumber\x12\"\n" +
	"\rroot_story_id\x18\x06 \x01(\tR\vrootStoryId\x12*\n" +
	"\x11previous_story_id\x18\a \x01(\tR\x0fpreviousStoryId\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf0\x01\n" +
	"\aChapter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bstory_id\x18\x02 \x01(\tR\astoryId\x12\x16\n" +
	"\x06number\x18\x03 \x01(\x05R\x06number\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xde\x02\n" +
	"\x05Scene\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bstory_id\x18\x02 \x01(\tR\astoryId\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x03 \x01(\tR\tchapterId\x12\x1b\n" +
	"\torder_num\x18\x04 \x01(\x05R\borderNum\x12\x12\n" +
	"\x04goal\x18\x05 \x01(\tR\x04goal\x12\x19\n" +
	"\btime_ref\x18\x06 \x01(\tR\atimeRef\x12(\n" +
	"\x10pov_character_id\x18\a \x01(\tR\x0epovCharacterId\x12\x1f\n" +
	"\vlocation_id\x18\b \x01(\tR\n" +
	"locationId\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"t\n" +
	"\x12CreateStoryRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12+\n" +
	"\x12created_by_user_id\x18\x03 \x01(\tR\x0fcreatedByUserId\"9\n" +
	"\x13CreateStoryResponse\x12\"\n" +
	"\x05story\x18\x01 \x01(\v2\f.story.StoryR\x05story\"!\n" +
	"\x0fGetStoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"6\n" +
	"\x10GetStoryResponse\x12\"\n" +
	"\x05story\x18\x01 \x01(\v2\f.story.StoryR\x05story\"l\n" +
	"\x12ListStoriesRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x129\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x19.common.PaginationRequestR\n" +
	"pagination\"^\n" +
	"\x13ListStoriesResponse\x12&\n" +
	"\astories\x18\x01 \x03(\v2\f.story.StoryR\astories\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"h\n" +
	"\x11CloneStoryRequest\x12&\n" +
	"\x0fsource_story_id\x18\x01 \x01(\tR\rsourceStoryId\x12+\n" +
	"\x12created_by_user_id\x18\x02 \x01(\tR\x0fcreatedByUserId\"f\n" +
	"\x12CloneStoryResponse\x12\"\n" +
	"\x05story\x18\x01 \x01(\v2\f.story.StoryR\x05story\x12,\n" +
	"\x12new_version_number\x18\x02 \x01(\x05R\x10newVersionNumber\">\n" +
	"\x18ListStoryVersionsRequest\x12\"\n" +
	"\rroot_story_id\x18\x01 \x01(\tR\vrootStoryId\"E\n" +
	"\x19ListStoryVersionsResponse\x12(\n" +
	"\bversions\x18\x01 \x03(\v2\f.story.StoryR\bversions2\xf2\x02\n" +
	"\fStoryService\x12D\n" +
	"\vCreateStory\x12\x19.story.CreateStoryRequest\x1a\x1a.story.CreateStoryResponse\x12;\n" +
	"\bGetStory\x12\x16.story.GetStoryRequest\x1a\x17.story.GetStoryResponse\x12D\n" +
	"\vListStories\x12\x19.story.ListStoriesRequest\x1a\x1a.story.ListStoriesResponse\x12A\n" +
	"\n" +
	"CloneStory\x12\x18.story.CloneStoryRequest\x1a\x19.story.CloneStoryResponse\x12V\n" +
	"\x11ListStoryVersions\x12\x1f.story.ListStoryVersionsRequest\x1a .story.ListStoryVersionsResponseB2Z0github.com/story-engine/main-service/proto/storyb\x06proto3"

var (
	file_proto_story_story_proto_rawDescOnce sync.Once
	file_proto_story_story_proto_rawDescData []byte
)

func file_proto_story_story_proto_rawDescGZIP() []byte {
	file_proto_story_story_proto_rawDescOnce.Do(func() {
		file_proto_story_story_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_story_story_proto_rawDesc), len(file_proto_story_story_proto_rawDesc)))
	})
	return file_proto_story_story_proto_rawDescData
}

var file_proto_story_story_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_story_story_proto_goTypes = []any{
	(*Story)(nil),                     // 0: story.Story
	(*Chapter)(nil),                   // 1: story.Chapter
	(*Scene)(nil),                     // 2: story.Scene
	(*CreateStoryRequest)(nil),        // 3: story.CreateStoryRequest
	(*CreateStoryResponse)(nil),       // 4: story.CreateStoryResponse
	(*GetStoryRequest)(nil),           // 5: story.GetStoryRequest
	(*GetStoryResponse)(nil),          // 6: story.GetStoryResponse
	(*ListStoriesRequest)(nil),        // 7: story.ListStoriesRequest
	(*ListStoriesResponse)(nil),       // 8: story.ListStoriesResponse
	(*CloneStoryRequest)(nil),         // 9: story.CloneStoryRequest
	(*CloneStoryResponse)(nil),        // 10: story.CloneStoryResponse
	(*ListStoryVersionsRequest)(nil),  // 11: story.ListStoryVersionsRequest
	(*ListStoryVersionsResponse)(nil), // 12: story.ListStoryVersionsResponse
	(*timestamppb.Timestamp)(nil),     // 13: google.protobuf.Timestamp
	(*common.PaginationRequest)(nil),  // 14: common.PaginationRequest
}
var file_proto_story_story_proto_depIdxs = []int32{
	13, // 0: story.Story.created_at:type_name -> google.protobuf.Timestamp
	13, // 1: story.Story.updated_at:type_name -> google.protobuf.Timestamp
	13, // 2: story.Chapter.created_at:type_name -> google.protobuf.Timestamp
	13, // 3: story.Chapter.updated_at:type_name -> google.protobuf.Timestamp
	13, // 4: story.Scene.created_at:type_name -> google.protobuf.Timestamp
	13, // 5: story.Scene.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 6: story.CreateStoryResponse.story:type_name -> story.Story
	0,  // 7: story.GetStoryResponse.story:type_name -> story.Story
	14, // 8: story.ListStoriesRequest.pagination:type_name -> common.PaginationRequest
	0,  // 9: story.ListStoriesResponse.stories:type_name -> story.Story
	0,  // 10: story.CloneStoryResponse.story:type_name -> story.Story
	0,  // 11: story.ListStoryVersionsResponse.versions:type_name -> story.Story
	3,  // 12: story.StoryService.CreateStory:input_type -> story.CreateStoryRequest
	5,  // 13: story.StoryService.GetStory:input_type -> story.GetStoryRequest
	7,  // 14: story.StoryService.ListStories:input_type -> story.ListStoriesRequest
	9,  // 15: story.StoryService.CloneStory:input_type -> story.CloneStoryRequest
	11, // 16: story.StoryService.ListStoryVersions:input_type -> story.ListStoryVersionsRequest
	4,  // 17: story.StoryService.CreateStory:output_type -> story.CreateStoryResponse
	6,  // 18: story.StoryService.GetStory:output_type -> story.GetStoryResponse
	8,  // 19: story.StoryService.ListStories:output_type -> story.ListStoriesResponse
	10, // 20: story.StoryService.CloneStory:output_type -> story.CloneStoryResponse
	12, // 21: story.StoryService.ListStoryVersions:output_type -> story.ListStoryVersionsResponse
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_story_story_proto_init() }
func file_proto_story_story_proto_init() {
	if File_proto_story_story_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_story_story_proto_rawDesc), len(file_proto_story_story_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_story_story_proto_goTypes,
		DependencyIndexes: file_proto_story_story_proto_depIdxs,
		MessageInfos:      file_proto_story_story_proto_msgTypes,
	}.Build()
	File_proto_story_story_proto = out.File
	file_proto_story_story_proto_goTypes = nil
	file_proto_story_story_proto_depIdxs = nil
}
