// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v6.33.2
// source: proto/scene/scene.proto

package scene

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Scene represents a scene in a chapter
type Scene struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StoryId        string                 `protobuf:"bytes,2,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	ChapterId      *string                `protobuf:"bytes,3,opt,name=chapter_id,json=chapterId,proto3,oneof" json:"chapter_id,omitempty"`
	OrderNum       int32                  `protobuf:"varint,4,opt,name=order_num,json=orderNum,proto3" json:"order_num,omitempty"`
	Goal           string                 `protobuf:"bytes,5,opt,name=goal,proto3" json:"goal,omitempty"`
	TimeRef        string                 `protobuf:"bytes,6,opt,name=time_ref,json=timeRef,proto3" json:"time_ref,omitempty"`
	PovCharacterId *string                `protobuf:"bytes,7,opt,name=pov_character_id,json=povCharacterId,proto3,oneof" json:"pov_character_id,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Scene) Reset() {
	*x = Scene{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_scene_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Scene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scene) ProtoMessage() {}

func (x *Scene) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_scene_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scene.ProtoReflect.Descriptor instead.
func (*Scene) Descriptor() ([]byte, []int) {
	return file_proto_scene_scene_proto_rawDescGZIP(), []int{0}
}

func (x *Scene) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Scene) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

func (x *Scene) GetChapterId() string {
	if x != nil && x.ChapterId != nil {
		return *x.ChapterId
	}
	return ""
}

func (x *Scene) GetOrderNum() int32 {
	if x != nil {
		return x.OrderNum
	}
	return 0
}

func (x *Scene) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *Scene) GetTimeRef() string {
	if x != nil {
		return x.TimeRef
	}
	return ""
}

func (x *Scene) GetPovCharacterId() string {
	if x != nil && x.PovCharacterId != nil {
		return *x.PovCharacterId
	}
	return ""
}

func (x *Scene) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Scene) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateSceneRequest is the request to create a new scene
type CreateSceneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StoryId        string  `protobuf:"bytes,1,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	ChapterId      *string `protobuf:"bytes,2,opt,name=chapter_id,json=chapterId,proto3,oneof" json:"chapter_id,omitempty"`
	OrderNum       int32   `protobuf:"varint,3,opt,name=order_num,json=orderNum,proto3" json:"order_num,omitempty"`
	PovCharacterId *string `protobuf:"bytes,4,opt,name=pov_character_id,json=povCharacterId,proto3,oneof" json:"pov_character_id,omitempty"`
	TimeRef        string  `protobuf:"bytes,5,opt,name=time_ref,json=timeRef,proto3" json:"time_ref,omitempty"`
	Goal           string  `protobuf:"bytes,6,opt,name=goal,proto3" json:"goal,omitempty"`
}

func (x *CreateSceneRequest) Reset() {
	*x = CreateSceneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_scene_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSceneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSceneRequest) ProtoMessage() {}

func (x *CreateSceneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_scene_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSceneRequest.ProtoReflect.Descriptor instead.
func (*CreateSceneRequest) Descriptor() ([]byte, []int) {
	return file_proto_scene_scene_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSceneRequest) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

func (x *CreateSceneRequest) GetChapterId() string {
	if x != nil && x.ChapterId != nil {
		return *x.ChapterId
	}
	return ""
}

func (x *CreateSceneRequest) GetOrderNum() int32 {
	if x != nil {
		return x.OrderNum
	}
	return 0
}

func (x *CreateSceneRequest) GetPovCharacterId() string {
	if x != nil && x.PovCharacterId != nil {
		return *x.PovCharacterId
	}
	return ""
}

func (x *CreateSceneRequest) GetTimeRef() string {
	if x != nil {
		return x.TimeRef
	}
	return ""
}

func (x *CreateSceneRequest) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

// CreateSceneResponse is the response after creating a scene
type CreateSceneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scene *Scene `protobuf:"bytes,1,opt,name=scene,proto3" json:"scene,omitempty"`
}

func (x *CreateSceneResponse) Reset() {
	*x = CreateSceneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_scene_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSceneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSceneResponse) ProtoMessage() {}

func (x *CreateSceneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_scene_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSceneResponse.ProtoReflect.Descriptor instead.
func (*CreateSceneResponse) Descriptor() ([]byte, []int) {
	return file_proto_scene_scene_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSceneResponse) GetScene() *Scene {
	if x != nil {
		return x.Scene
	}
	return nil
}

// GetSceneRequest is the request to get a scene by ID
type GetSceneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetSceneRequest) Reset() {
	*x = GetSceneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_scene_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSceneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSceneRequest) ProtoMessage() {}

func (x *GetSceneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_scene_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSceneRequest.ProtoReflect.Descriptor instead.
func (*GetSceneRequest) Descriptor() ([]byte, []int) {
	return file_proto_scene_scene_proto_rawDescGZIP(), []int{3}
}

func (x *GetSceneRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetSceneResponse is the response containing a scene
type GetSceneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scene *Scene `protobuf:"bytes,1,opt,name=scene,proto3" json:"scene,omitempty"`
}

func (x *GetSceneResponse) Reset() {
	*x = GetSceneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_scene_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSceneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSceneResponse) ProtoMessage() {}

func (x *GetSceneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_scene_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSceneResponse.ProtoReflect.Descriptor instead.
func (*GetSceneResponse) Descriptor() ([]byte, []int) {
	return file_proto_scene_scene_proto_rawDescGZIP(), []int{4}
}

func (x *GetSceneResponse) GetScene() *Scene {
	if x != nil {
		return x.Scene
	}
	return nil
}

// UpdateSceneRequest is the request to update a scene
type UpdateSceneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNum       *int32  `protobuf:"varint,2,opt,name=order_num,json=orderNum,proto3,oneof" json:"order_num,omitempty"`
	PovCharacterId *string `protobuf:"bytes,3,opt,name=pov_character_id,json=povCharacterId,proto3,oneof" json:"pov_character_id,omitempty"`
	TimeRef        *string `protobuf:"bytes,4,opt,name=time_ref,json=timeRef,proto3,oneof" json:"time_ref,omitempty"`
	Goal           *string `protobuf:"bytes,5,opt,name=goal,proto3,oneof" json:"goal,omitempty"`
}

func (x *UpdateSceneRequest) Reset() {
	*x = UpdateSceneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_scene_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSceneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSceneRequest) ProtoMessage() {}

func (x *UpdateSceneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_scene_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSceneRequest.ProtoReflect.Descriptor instead.
func (*UpdateSceneRequest) Descriptor() ([]byte, []int) {
	return file_proto_scene_scene_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateSceneRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSceneRequest) GetOrderNum() int32 {
	if x != nil && x.OrderNum != nil {
		return *x.OrderNum
	}
	return 0
}

func (x *UpdateSceneRequest) GetPovCharacterId() string {
	if x != nil && x.PovCharacterId != nil {
		return *x.PovCharacterId
	}
	return ""
}

func (x *UpdateSceneRequest) GetTimeRef() string {
	if x != nil && x.TimeRef != nil {
		return *x.TimeRef
	}
	return ""
}

func (x *UpdateSceneRequest) GetGoal() string {
	if x != nil && x.Goal != nil {
		return *x.Goal
	}
	return ""
}

// UpdateSceneResponse is the response after updating a scene
type UpdateSceneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scene *Scene `protobuf:"bytes,1,opt,name=scene,proto3" json:"scene,omitempty"`
}

func (x *UpdateSceneResponse) Reset() {
	*x = UpdateSceneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_scene_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSceneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSceneResponse) ProtoMessage() {}

func (x *UpdateSceneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_scene_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSceneResponse.ProtoReflect.Descriptor instead.
func (*UpdateSceneResponse) Descriptor() ([]byte, []int) {
	return file_proto_scene_scene_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateSceneResponse) GetScene() *Scene {
	if x != nil {
		return x.Scene
	}
	return nil
}

// DeleteSceneRequest is the request to delete a scene
type DeleteSceneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteSceneRequest) Reset() {
	*x = DeleteSceneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_scene_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSceneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSceneRequest) ProtoMessage() {}

func (x *DeleteSceneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_scene_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSceneRequest.ProtoReflect.Descriptor instead.
func (*DeleteSceneRequest) Descriptor() ([]byte, []int) {
	return file_proto_scene_scene_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSceneRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteSceneResponse is the response after deleting a scene
type DeleteSceneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteSceneResponse) Reset() {
	*x = DeleteSceneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_scene_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSceneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSceneResponse) ProtoMessage() {}

func (x *DeleteSceneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_scene_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSceneResponse.ProtoReflect.Descriptor instead.
func (*DeleteSceneResponse) Descriptor() ([]byte, []int) {
	return file_proto_scene_scene_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSceneResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// MoveSceneRequest is the request to move a scene to a different chapter
type MoveSceneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChapterId *string `protobuf:"bytes,2,opt,name=chapter_id,json=chapterId,proto3,oneof" json:"chapter_id,omitempty"` // null to unassign from chapter
}

func (x *MoveSceneRequest) Reset() {
	*x = MoveSceneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_scene_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveSceneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveSceneRequest) ProtoMessage() {}

func (x *MoveSceneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_scene_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveSceneRequest.ProtoReflect.Descriptor instead.
func (*MoveSceneRequest) Descriptor() ([]byte, []int) {
	return file_proto_scene_scene_proto_rawDescGZIP(), []int{9}
}

func (x *MoveSceneRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MoveSceneRequest) GetChapterId() string {
	if x != nil && x.ChapterId != nil {
		return *x.ChapterId
	}
	return ""
}

// MoveSceneResponse is the response after moving a scene
type MoveSceneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scene *Scene `protobuf:"bytes,1,opt,name=scene,proto3" json:"scene,omitempty"`
}

func (x *MoveSceneResponse) Reset() {
	*x = MoveSceneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_scene_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveSceneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveSceneResponse) ProtoMessage() {}

func (x *MoveSceneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_scene_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveSceneResponse.ProtoReflect.Descriptor instead.
func (*MoveSceneResponse) Descriptor() ([]byte, []int) {
	return file_proto_scene_scene_proto_rawDescGZIP(), []int{10}
}

func (x *MoveSceneResponse) GetScene() *Scene {
	if x != nil {
		return x.Scene
	}
	return nil
}

// ListScenesByChapterRequest is the request to list scenes for a chapter
type ListScenesByChapterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChapterId string `protobuf:"bytes,1,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
}

func (x *ListScenesByChapterRequest) Reset() {
	*x = ListScenesByChapterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_scene_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListScenesByChapterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScenesByChapterRequest) ProtoMessage() {}

func (x *ListScenesByChapterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_scene_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScenesByChapterRequest.ProtoReflect.Descriptor instead.
func (*ListScenesByChapterRequest) Descriptor() ([]byte, []int) {
	return file_proto_scene_scene_proto_rawDescGZIP(), []int{11}
}

func (x *ListScenesByChapterRequest) GetChapterId() string {
	if x != nil {
		return x.ChapterId
	}
	return ""
}

// ListScenesByChapterResponse is the response containing scenes for a chapter
type ListScenesByChapterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scenes     []*Scene `protobuf:"bytes,1,rep,name=scenes,proto3" json:"scenes,omitempty"`
	TotalCount int32    `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
}

func (x *ListScenesByChapterResponse) Reset() {
	*x = ListScenesByChapterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_scene_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListScenesByChapterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScenesByChapterResponse) ProtoMessage() {}

func (x *ListScenesByChapterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_scene_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScenesByChapterResponse.ProtoReflect.Descriptor instead.
func (*ListScenesByChapterResponse) Descriptor() ([]byte, []int) {
	return file_proto_scene_scene_proto_rawDescGZIP(), []int{12}
}

func (x *ListScenesByChapterResponse) GetScenes() []*Scene {
	if x != nil {
		return x.Scenes
	}
	return nil
}

func (x *ListScenesByChapterResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// ListScenesByStoryRequest is the request to list all scenes for a story
type ListScenesByStoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StoryId string `protobuf:"bytes,1,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
}

func (x *ListScenesByStoryRequest) Reset() {
	*x = ListScenesByStoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_scene_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListScenesByStoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScenesByStoryRequest) ProtoMessage() {}

func (x *ListScenesByStoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_scene_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScenesByStoryRequest.ProtoReflect.Descriptor instead.
func (*ListScenesByStoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_scene_scene_proto_rawDescGZIP(), []int{13}
}

func (x *ListScenesByStoryRequest) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

// ListScenesByStoryResponse is the response containing all scenes for a story
type ListScenesByStoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scenes     []*Scene `protobuf:"bytes,1,rep,name=scenes,proto3" json:"scenes,omitempty"`
	TotalCount int32    `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
}

func (x *ListScenesByStoryResponse) Reset() {
	*x = ListScenesByStoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_scene_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListScenesByStoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScenesByStoryResponse) ProtoMessage() {}

func (x *ListScenesByStoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_scene_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScenesByStoryResponse.ProtoReflect.Descriptor instead.
func (*ListScenesByStoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_scene_scene_proto_rawDescGZIP(), []int{14}
}

func (x *ListScenesByStoryResponse) GetScenes() []*Scene {
	if x != nil {
		return x.Scenes
	}
	return nil
}

func (x *ListScenesByStoryResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// SceneReference represents a reference from a scene to an entity
type SceneReference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SceneId    string                 `protobuf:"bytes,2,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	EntityType string                 `protobuf:"bytes,3,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"` // "character", "location", or "artifact"
	EntityId   string                 `protobuf:"bytes,4,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	CreatedAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *SceneReference) Reset() {
	*x = SceneReference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_scene_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SceneReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneReference) ProtoMessage() {}

func (x *SceneReference) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_scene_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneReference.ProtoReflect.Descriptor instead.
func (*SceneReference) Descriptor() ([]byte, []int) {
	return file_proto_scene_scene_proto_rawDescGZIP(), []int{15}
}

func (x *SceneReference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SceneReference) GetSceneId() string {
	if x != nil {
		return x.SceneId
	}
	return ""
}

func (x *SceneReference) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *SceneReference) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *SceneReference) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// GetSceneReferencesRequest is the request to get references for a scene
type GetSceneReferencesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SceneId string `protobuf:"bytes,1,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
}

func (x *GetSceneReferencesRequest) Reset() {
	*x = GetSceneReferencesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_scene_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSceneReferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSceneReferencesRequest) ProtoMessage() {}

func (x *GetSceneReferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_scene_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSceneReferencesRequest.ProtoReflect.Descriptor instead.
func (*GetSceneReferencesRequest) Descriptor() ([]byte, []int) {
	return file_proto_scene_scene_proto_rawDescGZIP(), []int{16}
}

func (x *GetSceneReferencesRequest) GetSceneId() string {
	if x != nil {
		return x.SceneId
	}
	return ""
}

// GetSceneReferencesResponse is the response containing scene references
type GetSceneReferencesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	References []*SceneReference `protobuf:"bytes,1,rep,name=references,proto3" json:"references,omitempty"`
	TotalCount int32             `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
}

func (x *GetSceneReferencesResponse) Reset() {
	*x = GetSceneReferencesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_scene_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSceneReferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSceneReferencesResponse) ProtoMessage() {}

func (x *GetSceneReferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_scene_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSceneReferencesResponse.ProtoReflect.Descriptor instead.
func (*GetSceneReferencesResponse) Descriptor() ([]byte, []int) {
	return file_proto_scene_scene_proto_rawDescGZIP(), []int{17}
}

func (x *GetSceneReferencesResponse) GetReferences() []*SceneReference {
	if x != nil {
		return x.References
	}
	return nil
}

func (x *GetSceneReferencesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// AddSceneReferenceRequest is the request to add a reference to a scene
type AddSceneReferenceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SceneId    string `protobuf:"bytes,1,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	EntityType string `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"` // "character", "location", or "artifact"
	EntityId   string `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
}

func (x *AddSceneReferenceRequest) Reset() {
	*x = AddSceneReferenceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_scene_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSceneReferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSceneReferenceRequest) ProtoMessage() {}

func (x *AddSceneReferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_scene_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSceneReferenceRequest.ProtoReflect.Descriptor instead.
func (*AddSceneReferenceRequest) Descriptor() ([]byte, []int) {
	return file_proto_scene_scene_proto_rawDescGZIP(), []int{18}
}

func (x *AddSceneReferenceRequest) GetSceneId() string {
	if x != nil {
		return x.SceneId
	}
	return ""
}

func (x *AddSceneReferenceRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *AddSceneReferenceRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

// AddSceneReferenceResponse is the response after adding a scene reference
type AddSceneReferenceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reference *SceneReference `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
}

func (x *AddSceneReferenceResponse) Reset() {
	*x = AddSceneReferenceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_scene_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSceneReferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSceneReferenceResponse) ProtoMessage() {}

func (x *AddSceneReferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_scene_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSceneReferenceResponse.ProtoReflect.Descriptor instead.
func (*AddSceneReferenceResponse) Descriptor() ([]byte, []int) {
	return file_proto_scene_scene_proto_rawDescGZIP(), []int{19}
}

func (x *AddSceneReferenceResponse) GetReference() *SceneReference {
	if x != nil {
		return x.Reference
	}
	return nil
}

// RemoveSceneReferenceRequest is the request to remove a reference from a scene
type RemoveSceneReferenceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SceneId    string `protobuf:"bytes,1,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	EntityType string `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"` // "character", "location", or "artifact"
	EntityId   string `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
}

func (x *RemoveSceneReferenceRequest) Reset() {
	*x = RemoveSceneReferenceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_scene_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveSceneReferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSceneReferenceRequest) ProtoMessage() {}

func (x *RemoveSceneReferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_scene_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSceneReferenceRequest.ProtoReflect.Descriptor instead.
func (*RemoveSceneReferenceRequest) Descriptor() ([]byte, []int) {
	return file_proto_scene_scene_proto_rawDescGZIP(), []int{20}
}

func (x *RemoveSceneReferenceRequest) GetSceneId() string {
	if x != nil {
		return x.SceneId
	}
	return ""
}

func (x *RemoveSceneReferenceRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *RemoveSceneReferenceRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

// RemoveSceneReferenceResponse is the response after removing a scene reference
type RemoveSceneReferenceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveSceneReferenceResponse) Reset() {
	*x = RemoveSceneReferenceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_scene_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveSceneReferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSceneReferenceResponse) ProtoMessage() {}

func (x *RemoveSceneReferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_scene_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSceneReferenceResponse.ProtoReflect.Descriptor instead.
func (*RemoveSceneReferenceResponse) Descriptor() ([]byte, []int) {
	return file_proto_scene_scene_proto_rawDescGZIP(), []int{21}
}

var File_proto_scene_scene_proto protoreflect.FileDescriptor

var file_proto_scene_scene_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x2f, 0x73, 0x63,
	0x65, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xeb, 0x02, 0x0a, 0x05, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x63, 0x68,
	0x61, 0x70, 0x74, 0x65, 0x72, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x6f, 0x61, 0x6c, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x67, 0x6f, 0x61, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x74,
	0x69, 0x6d, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74,
	0x69, 0x6d, 0x65, 0x52, 0x65, 0x66, 0x12, 0x2d, 0x0a, 0x10, 0x70, 0x6f, 0x76, 0x5f, 0x63, 0x68,
	0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x01, 0x52, 0x0e, 0x70, 0x6f, 0x76, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x42, 0x0d, 0x0a, 0x0b, 0x5f,
	0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x42, 0x13, 0x0a, 0x11, 0x5f, 0x70,
	0x6f, 0x76, 0x5f, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x22,
	0xf2, 0x01, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x49,
	0x64, 0x12, 0x22, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72,
	0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x6e,
	0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e,
	0x75, 0x6d, 0x12, 0x2d, 0x0a, 0x10, 0x70, 0x6f, 0x76, 0x5f, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0e,
	0x70, 0x6f, 0x76, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x64, 0x88, 0x01,
	0x01, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x66, 0x12, 0x12, 0x0a, 0x04,
	0x67, 0x6f, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x67, 0x6f, 0x61, 0x6c,
	0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x42,
	0x13, 0x0a, 0x11, 0x5f, 0x70, 0x6f, 0x76, 0x5f, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x22, 0x39, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x63,
	0x65, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x73,
	0x63, 0x65, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x63, 0x65,
	0x6e, 0x65, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x22,
	0x21, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x36, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x2e, 0x53, 0x63,
	0x65, 0x6e, 0x65, 0x52, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x22, 0xe7, 0x01, 0x0a, 0x12, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x20, 0x0a, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d,
	0x88, 0x01, 0x01, 0x12, 0x2d, 0x0a, 0x10, 0x70, 0x6f, 0x76, 0x5f, 0x63, 0x68, 0x61, 0x72, 0x61,
	0x63, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52,
	0x0e, 0x70, 0x6f, 0x76, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x64, 0x88,
	0x01, 0x01, 0x12, 0x1e, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x66, 0x88,
	0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x67, 0x6f, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x03, 0x52, 0x04, 0x67, 0x6f, 0x61, 0x6c, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x75, 0x6d, 0x42, 0x13, 0x0a, 0x11, 0x5f, 0x70, 0x6f,
	0x76, 0x5f, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x42, 0x0b,
	0x0a, 0x09, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x42, 0x07, 0x0a, 0x05, 0x5f,
	0x67, 0x6f, 0x61, 0x6c, 0x22, 0x39, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x63,
	0x65, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x73,
	0x63, 0x65, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x63, 0x65,
	0x6e, 0x65, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x22,
	0x24, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2f, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53,
	0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x55, 0x0a, 0x10, 0x4d, 0x6f, 0x76, 0x65, 0x53, 0x63,
	0x65, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0a, 0x63, 0x68,
	0x61, 0x70, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x09, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x49, 0x64, 0x88, 0x01, 0x01, 0x42, 0x0d,
	0x0a, 0x0b, 0x5f, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x22, 0x37, 0x0a,
	0x11, 0x4d, 0x6f, 0x76, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52,
	0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x22, 0x3b, 0x0a, 0x1a, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x63,
	0x65, 0x6e, 0x65, 0x73, 0x42, 0x79, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x64, 0x0a, 0x1b, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x65,
	0x73, 0x42, 0x79, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x65,
	0x52, 0x06, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x35, 0x0a, 0x18, 0x4c, 0x69, 0x73,
	0x74, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x73, 0x42, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64,
	0x22, 0x62, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x73, 0x42, 0x79,
	0x53, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a,
	0x06, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x73, 0x63, 0x65, 0x6e, 0x65, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x06, 0x73, 0x63, 0x65,
	0x6e, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0xb4, 0x01, 0x0a, 0x0e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x63, 0x65, 0x6e, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65,
	0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64,
	0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x36, 0x0a, 0x19, 0x47,
	0x65, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x63, 0x65, 0x6e,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x63, 0x65, 0x6e,
	0x65, 0x49, 0x64, 0x22, 0x74, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x35, 0x0a, 0x0a, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x2e, 0x53, 0x63,
	0x65, 0x6e, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x0a, 0x72, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x73, 0x0a, 0x18, 0x41, 0x64, 0x64,
	0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64,
	0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x22, 0x50,
	0x0a, 0x19, 0x41, 0x64, 0x64, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x09, 0x72,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x22, 0x76, 0x0a, 0x1b, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x19, 0x0a, 0x08, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x22, 0x1e, 0x0a, 0x1c, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xa7, 0x06, 0x0a, 0x0c, 0x53, 0x63, 0x65,
	0x6e, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x12, 0x19, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x65,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3b, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x12, 0x16, 0x2e, 0x73, 0x63,
	0x65, 0x6e, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53,
	0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0b,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x12, 0x19, 0x2e, 0x73, 0x63,
	0x65, 0x6e, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x63, 0x65, 0x6e,
	0x65, 0x12, 0x19, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x73,
	0x63, 0x65, 0x6e, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x09, 0x4d, 0x6f, 0x76, 0x65,
	0x53, 0x63, 0x65, 0x6e, 0x65, 0x12, 0x17, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x2e, 0x4d, 0x6f,
	0x76, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18,
	0x2e, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5c, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74,
	0x53, 0x63, 0x65, 0x6e, 0x65, 0x73, 0x42, 0x79, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x12,
	0x21, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x63, 0x65, 0x6e,
	0x65, 0x73, 0x42, 0x79, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x22, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53,
	0x63, 0x65, 0x6e, 0x65, 0x73, 0x42, 0x79, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x63,
	0x65, 0x6e, 0x65, 0x73, 0x42, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x1f, 0x2e, 0x73, 0x63,
	0x65, 0x6e, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x73, 0x42, 0x79,
	0x53, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x73,
	0x63, 0x65, 0x6e, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x73, 0x42,
	0x79, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x73, 0x12, 0x20, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x11, 0x41, 0x64, 0x64,
	0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x1f,
	0x2e, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x20, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x63, 0x65, 0x6e, 0x65,
	0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x5f, 0x0a, 0x14, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65,
	0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x22, 0x2e, 0x73, 0x63, 0x65, 0x6e,
	0x65, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e,
	0x73, 0x63, 0x65, 0x6e, 0x65, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x63, 0x65, 0x6e,
	0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2d, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x6d, 0x61,
	0x69, 0x6e, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_scene_scene_proto_rawDescOnce sync.Once
	file_proto_scene_scene_proto_rawDescData = file_proto_scene_scene_proto_rawDesc
)

func file_proto_scene_scene_proto_rawDescGZIP() []byte {
	file_proto_scene_scene_proto_rawDescOnce.Do(func() {
		file_proto_scene_scene_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_scene_scene_proto_rawDescData)
	})
	return file_proto_scene_scene_proto_rawDescData
}

var file_proto_scene_scene_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_scene_scene_proto_goTypes = []interface{}{
	(*Scene)(nil),                        // 0: scene.Scene
	(*CreateSceneRequest)(nil),           // 1: scene.CreateSceneRequest
	(*CreateSceneResponse)(nil),          // 2: scene.CreateSceneResponse
	(*GetSceneRequest)(nil),              // 3: scene.GetSceneRequest
	(*GetSceneResponse)(nil),             // 4: scene.GetSceneResponse
	(*UpdateSceneRequest)(nil),           // 5: scene.UpdateSceneRequest
	(*UpdateSceneResponse)(nil),          // 6: scene.UpdateSceneResponse
	(*DeleteSceneRequest)(nil),           // 7: scene.DeleteSceneRequest
	(*DeleteSceneResponse)(nil),          // 8: scene.DeleteSceneResponse
	(*MoveSceneRequest)(nil),             // 9: scene.MoveSceneRequest
	(*MoveSceneResponse)(nil),            // 10: scene.MoveSceneResponse
	(*ListScenesByChapterRequest)(nil),   // 11: scene.ListScenesByChapterRequest
	(*ListScenesByChapterResponse)(nil),  // 12: scene.ListScenesByChapterResponse
	(*ListScenesByStoryRequest)(nil),     // 13: scene.ListScenesByStoryRequest
	(*ListScenesByStoryResponse)(nil),    // 14: scene.ListScenesByStoryResponse
	(*SceneReference)(nil),               // 15: scene.SceneReference
	(*GetSceneReferencesRequest)(nil),    // 16: scene.GetSceneReferencesRequest
	(*GetSceneReferencesResponse)(nil),   // 17: scene.GetSceneReferencesResponse
	(*AddSceneReferenceRequest)(nil),     // 18: scene.AddSceneReferenceRequest
	(*AddSceneReferenceResponse)(nil),    // 19: scene.AddSceneReferenceResponse
	(*RemoveSceneReferenceRequest)(nil),  // 20: scene.RemoveSceneReferenceRequest
	(*RemoveSceneReferenceResponse)(nil), // 21: scene.RemoveSceneReferenceResponse
	(*timestamppb.Timestamp)(nil),        // 22: google.protobuf.Timestamp
}
var file_proto_scene_scene_proto_depIdxs = []int32{
	22, // 0: scene.Scene.created_at:type_name -> google.protobuf.Timestamp
	22, // 1: scene.Scene.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: scene.CreateSceneResponse.scene:type_name -> scene.Scene
	0,  // 3: scene.GetSceneResponse.scene:type_name -> scene.Scene
	0,  // 4: scene.UpdateSceneResponse.scene:type_name -> scene.Scene
	0,  // 5: scene.MoveSceneResponse.scene:type_name -> scene.Scene
	0,  // 6: scene.ListScenesByChapterResponse.scenes:type_name -> scene.Scene
	0,  // 7: scene.ListScenesByStoryResponse.scenes:type_name -> scene.Scene
	22, // 8: scene.SceneReference.created_at:type_name -> google.protobuf.Timestamp
	15, // 9: scene.GetSceneReferencesResponse.references:type_name -> scene.SceneReference
	15, // 10: scene.AddSceneReferenceResponse.reference:type_name -> scene.SceneReference
	1,  // 11: scene.SceneService.CreateScene:input_type -> scene.CreateSceneRequest
	3,  // 12: scene.SceneService.GetScene:input_type -> scene.GetSceneRequest
	5,  // 13: scene.SceneService.UpdateScene:input_type -> scene.UpdateSceneRequest
	7,  // 14: scene.SceneService.DeleteScene:input_type -> scene.DeleteSceneRequest
	9,  // 15: scene.SceneService.MoveScene:input_type -> scene.MoveSceneRequest
	11, // 16: scene.SceneService.ListScenesByChapter:input_type -> scene.ListScenesByChapterRequest
	13, // 17: scene.SceneService.ListScenesByStory:input_type -> scene.ListScenesByStoryRequest
	16, // 18: scene.SceneService.GetSceneReferences:input_type -> scene.GetSceneReferencesRequest
	18, // 19: scene.SceneService.AddSceneReference:input_type -> scene.AddSceneReferenceRequest
	20, // 20: scene.SceneService.RemoveSceneReference:input_type -> scene.RemoveSceneReferenceRequest
	2,  // 21: scene.SceneService.CreateScene:output_type -> scene.CreateSceneResponse
	4,  // 22: scene.SceneService.GetScene:output_type -> scene.GetSceneResponse
	6,  // 23: scene.SceneService.UpdateScene:output_type -> scene.UpdateSceneResponse
	8,  // 24: scene.SceneService.DeleteScene:output_type -> scene.DeleteSceneResponse
	10, // 25: scene.SceneService.MoveScene:output_type -> scene.MoveSceneResponse
	12, // 26: scene.SceneService.ListScenesByChapter:output_type -> scene.ListScenesByChapterResponse
	14, // 27: scene.SceneService.ListScenesByStory:output_type -> scene.ListScenesByStoryResponse
	17, // 28: scene.SceneService.GetSceneReferences:output_type -> scene.GetSceneReferencesResponse
	19, // 29: scene.SceneService.AddSceneReference:output_type -> scene.AddSceneReferenceResponse
	21, // 30: scene.SceneService.RemoveSceneReference:output_type -> scene.RemoveSceneReferenceResponse
	21, // [21:31] is the sub-list for method output_type
	11, // [11:21] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_scene_scene_proto_init() }
func file_proto_scene_scene_proto_init() {
	if File_proto_scene_scene_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_scene_scene_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Scene); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scene_scene_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSceneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scene_scene_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSceneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scene_scene_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSceneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scene_scene_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSceneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scene_scene_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSceneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scene_scene_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSceneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scene_scene_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSceneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scene_scene_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSceneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scene_scene_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveSceneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scene_scene_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveSceneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scene_scene_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListScenesByChapterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scene_scene_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListScenesByChapterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scene_scene_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListScenesByStoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scene_scene_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListScenesByStoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scene_scene_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SceneReference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scene_scene_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSceneReferencesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scene_scene_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSceneReferencesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scene_scene_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSceneReferenceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scene_scene_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSceneReferenceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scene_scene_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveSceneReferenceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scene_scene_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveSceneReferenceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_scene_scene_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_proto_scene_scene_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_proto_scene_scene_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_proto_scene_scene_proto_msgTypes[9].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_scene_scene_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scene_scene_proto_goTypes,
		DependencyIndexes: file_proto_scene_scene_proto_depIdxs,
		MessageInfos:      file_proto_scene_scene_proto_msgTypes,
	}.Build()
	File_proto_scene_scene_proto = out.File
	file_proto_scene_scene_proto_rawDesc = nil
	file_proto_scene_scene_proto_goTypes = nil
	file_proto_scene_scene_proto_depIdxs = nil
}
