// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.2
// source: proto/event/event.proto

package event

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	EventService_CreateEvent_FullMethodName          = "/event.EventService/CreateEvent"
	EventService_GetEvent_FullMethodName             = "/event.EventService/GetEvent"
	EventService_ListEvents_FullMethodName           = "/event.EventService/ListEvents"
	EventService_UpdateEvent_FullMethodName          = "/event.EventService/UpdateEvent"
	EventService_DeleteEvent_FullMethodName          = "/event.EventService/DeleteEvent"
	EventService_AddEventReference_FullMethodName    = "/event.EventService/AddEventReference"
	EventService_RemoveEventReference_FullMethodName = "/event.EventService/RemoveEventReference"
	EventService_GetEventReferences_FullMethodName   = "/event.EventService/GetEventReferences"
	EventService_UpdateEventReference_FullMethodName = "/event.EventService/UpdateEventReference"
	EventService_GetEventChildren_FullMethodName     = "/event.EventService/GetEventChildren"
	EventService_GetEventAncestors_FullMethodName    = "/event.EventService/GetEventAncestors"
	EventService_GetEventDescendants_FullMethodName  = "/event.EventService/GetEventDescendants"
	EventService_MoveEvent_FullMethodName            = "/event.EventService/MoveEvent"
	EventService_SetEventEpoch_FullMethodName        = "/event.EventService/SetEventEpoch"
	EventService_GetEventEpoch_FullMethodName        = "/event.EventService/GetEventEpoch"
	EventService_GetTimeline_FullMethodName          = "/event.EventService/GetTimeline"
)

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventServiceClient interface {
	// CreateEvent creates a new event
	CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (*CreateEventResponse, error)
	// GetEvent retrieves an event by ID
	GetEvent(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (*GetEventResponse, error)
	// ListEvents lists events for a world
	ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error)
	// UpdateEvent updates an existing event
	UpdateEvent(ctx context.Context, in *UpdateEventRequest, opts ...grpc.CallOption) (*UpdateEventResponse, error)
	// DeleteEvent deletes an event
	DeleteEvent(ctx context.Context, in *DeleteEventRequest, opts ...grpc.CallOption) (*DeleteEventResponse, error)
	// AddEventReference adds a reference to an event
	AddEventReference(ctx context.Context, in *AddEventReferenceRequest, opts ...grpc.CallOption) (*AddEventReferenceResponse, error)
	// RemoveEventReference removes a reference from an event
	RemoveEventReference(ctx context.Context, in *RemoveEventReferenceRequest, opts ...grpc.CallOption) (*RemoveEventReferenceResponse, error)
	// GetEventReferences lists references for an event
	GetEventReferences(ctx context.Context, in *GetEventReferencesRequest, opts ...grpc.CallOption) (*GetEventReferencesResponse, error)
	// UpdateEventReference updates an event reference
	UpdateEventReference(ctx context.Context, in *UpdateEventReferenceRequest, opts ...grpc.CallOption) (*UpdateEventReferenceResponse, error)
	// GetEventChildren retrieves direct children of an event
	GetEventChildren(ctx context.Context, in *GetEventChildrenRequest, opts ...grpc.CallOption) (*GetEventChildrenResponse, error)
	// GetEventAncestors retrieves ancestors of an event
	GetEventAncestors(ctx context.Context, in *GetEventAncestorsRequest, opts ...grpc.CallOption) (*GetEventAncestorsResponse, error)
	// GetEventDescendants retrieves descendants of an event
	GetEventDescendants(ctx context.Context, in *GetEventDescendantsRequest, opts ...grpc.CallOption) (*GetEventDescendantsResponse, error)
	// MoveEvent moves an event to another parent
	MoveEvent(ctx context.Context, in *MoveEventRequest, opts ...grpc.CallOption) (*MoveEventResponse, error)
	// SetEventEpoch sets an event as epoch
	SetEventEpoch(ctx context.Context, in *SetEventEpochRequest, opts ...grpc.CallOption) (*SetEventEpochResponse, error)
	// GetEventEpoch retrieves the epoch event for a world
	GetEventEpoch(ctx context.Context, in *GetEventEpochRequest, opts ...grpc.CallOption) (*GetEventEpochResponse, error)
	// GetTimeline retrieves events ordered by timeline position
	GetTimeline(ctx context.Context, in *GetTimelineRequest, opts ...grpc.CallOption) (*GetTimelineResponse, error)
}

type eventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventServiceClient(cc grpc.ClientConnInterface) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (*CreateEventResponse, error) {
	out := new(CreateEventResponse)
	err := c.cc.Invoke(ctx, EventService_CreateEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetEvent(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (*GetEventResponse, error) {
	out := new(GetEventResponse)
	err := c.cc.Invoke(ctx, EventService_GetEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error) {
	out := new(ListEventsResponse)
	err := c.cc.Invoke(ctx, EventService_ListEvents_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) UpdateEvent(ctx context.Context, in *UpdateEventRequest, opts ...grpc.CallOption) (*UpdateEventResponse, error) {
	out := new(UpdateEventResponse)
	err := c.cc.Invoke(ctx, EventService_UpdateEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) DeleteEvent(ctx context.Context, in *DeleteEventRequest, opts ...grpc.CallOption) (*DeleteEventResponse, error) {
	out := new(DeleteEventResponse)
	err := c.cc.Invoke(ctx, EventService_DeleteEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) AddEventReference(ctx context.Context, in *AddEventReferenceRequest, opts ...grpc.CallOption) (*AddEventReferenceResponse, error) {
	out := new(AddEventReferenceResponse)
	err := c.cc.Invoke(ctx, EventService_AddEventReference_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) RemoveEventReference(ctx context.Context, in *RemoveEventReferenceRequest, opts ...grpc.CallOption) (*RemoveEventReferenceResponse, error) {
	out := new(RemoveEventReferenceResponse)
	err := c.cc.Invoke(ctx, EventService_RemoveEventReference_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetEventReferences(ctx context.Context, in *GetEventReferencesRequest, opts ...grpc.CallOption) (*GetEventReferencesResponse, error) {
	out := new(GetEventReferencesResponse)
	err := c.cc.Invoke(ctx, EventService_GetEventReferences_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) UpdateEventReference(ctx context.Context, in *UpdateEventReferenceRequest, opts ...grpc.CallOption) (*UpdateEventReferenceResponse, error) {
	out := new(UpdateEventReferenceResponse)
	err := c.cc.Invoke(ctx, EventService_UpdateEventReference_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetEventChildren(ctx context.Context, in *GetEventChildrenRequest, opts ...grpc.CallOption) (*GetEventChildrenResponse, error) {
	out := new(GetEventChildrenResponse)
	err := c.cc.Invoke(ctx, EventService_GetEventChildren_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetEventAncestors(ctx context.Context, in *GetEventAncestorsRequest, opts ...grpc.CallOption) (*GetEventAncestorsResponse, error) {
	out := new(GetEventAncestorsResponse)
	err := c.cc.Invoke(ctx, EventService_GetEventAncestors_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetEventDescendants(ctx context.Context, in *GetEventDescendantsRequest, opts ...grpc.CallOption) (*GetEventDescendantsResponse, error) {
	out := new(GetEventDescendantsResponse)
	err := c.cc.Invoke(ctx, EventService_GetEventDescendants_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) MoveEvent(ctx context.Context, in *MoveEventRequest, opts ...grpc.CallOption) (*MoveEventResponse, error) {
	out := new(MoveEventResponse)
	err := c.cc.Invoke(ctx, EventService_MoveEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) SetEventEpoch(ctx context.Context, in *SetEventEpochRequest, opts ...grpc.CallOption) (*SetEventEpochResponse, error) {
	out := new(SetEventEpochResponse)
	err := c.cc.Invoke(ctx, EventService_SetEventEpoch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetEventEpoch(ctx context.Context, in *GetEventEpochRequest, opts ...grpc.CallOption) (*GetEventEpochResponse, error) {
	out := new(GetEventEpochResponse)
	err := c.cc.Invoke(ctx, EventService_GetEventEpoch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetTimeline(ctx context.Context, in *GetTimelineRequest, opts ...grpc.CallOption) (*GetTimelineResponse, error) {
	out := new(GetTimelineResponse)
	err := c.cc.Invoke(ctx, EventService_GetTimeline_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServiceServer is the server API for EventService service.
// All implementations must embed UnimplementedEventServiceServer
// for forward compatibility
type EventServiceServer interface {
	// CreateEvent creates a new event
	CreateEvent(context.Context, *CreateEventRequest) (*CreateEventResponse, error)
	// GetEvent retrieves an event by ID
	GetEvent(context.Context, *GetEventRequest) (*GetEventResponse, error)
	// ListEvents lists events for a world
	ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error)
	// UpdateEvent updates an existing event
	UpdateEvent(context.Context, *UpdateEventRequest) (*UpdateEventResponse, error)
	// DeleteEvent deletes an event
	DeleteEvent(context.Context, *DeleteEventRequest) (*DeleteEventResponse, error)
	// AddEventReference adds a reference to an event
	AddEventReference(context.Context, *AddEventReferenceRequest) (*AddEventReferenceResponse, error)
	// RemoveEventReference removes a reference from an event
	RemoveEventReference(context.Context, *RemoveEventReferenceRequest) (*RemoveEventReferenceResponse, error)
	// GetEventReferences lists references for an event
	GetEventReferences(context.Context, *GetEventReferencesRequest) (*GetEventReferencesResponse, error)
	// UpdateEventReference updates an event reference
	UpdateEventReference(context.Context, *UpdateEventReferenceRequest) (*UpdateEventReferenceResponse, error)
	// GetEventChildren retrieves direct children of an event
	GetEventChildren(context.Context, *GetEventChildrenRequest) (*GetEventChildrenResponse, error)
	// GetEventAncestors retrieves ancestors of an event
	GetEventAncestors(context.Context, *GetEventAncestorsRequest) (*GetEventAncestorsResponse, error)
	// GetEventDescendants retrieves descendants of an event
	GetEventDescendants(context.Context, *GetEventDescendantsRequest) (*GetEventDescendantsResponse, error)
	// MoveEvent moves an event to another parent
	MoveEvent(context.Context, *MoveEventRequest) (*MoveEventResponse, error)
	// SetEventEpoch sets an event as epoch
	SetEventEpoch(context.Context, *SetEventEpochRequest) (*SetEventEpochResponse, error)
	// GetEventEpoch retrieves the epoch event for a world
	GetEventEpoch(context.Context, *GetEventEpochRequest) (*GetEventEpochResponse, error)
	// GetTimeline retrieves events ordered by timeline position
	GetTimeline(context.Context, *GetTimelineRequest) (*GetTimelineResponse, error)
	mustEmbedUnimplementedEventServiceServer()
}

// UnimplementedEventServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEventServiceServer struct {
}

func (UnimplementedEventServiceServer) CreateEvent(context.Context, *CreateEventRequest) (*CreateEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEvent not implemented")
}
func (UnimplementedEventServiceServer) GetEvent(context.Context, *GetEventRequest) (*GetEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEvent not implemented")
}
func (UnimplementedEventServiceServer) ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEvents not implemented")
}
func (UnimplementedEventServiceServer) UpdateEvent(context.Context, *UpdateEventRequest) (*UpdateEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEvent not implemented")
}
func (UnimplementedEventServiceServer) DeleteEvent(context.Context, *DeleteEventRequest) (*DeleteEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEvent not implemented")
}
func (UnimplementedEventServiceServer) AddEventReference(context.Context, *AddEventReferenceRequest) (*AddEventReferenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddEventReference not implemented")
}
func (UnimplementedEventServiceServer) RemoveEventReference(context.Context, *RemoveEventReferenceRequest) (*RemoveEventReferenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveEventReference not implemented")
}
func (UnimplementedEventServiceServer) GetEventReferences(context.Context, *GetEventReferencesRequest) (*GetEventReferencesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEventReferences not implemented")
}
func (UnimplementedEventServiceServer) UpdateEventReference(context.Context, *UpdateEventReferenceRequest) (*UpdateEventReferenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEventReference not implemented")
}
func (UnimplementedEventServiceServer) GetEventChildren(context.Context, *GetEventChildrenRequest) (*GetEventChildrenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEventChildren not implemented")
}
func (UnimplementedEventServiceServer) GetEventAncestors(context.Context, *GetEventAncestorsRequest) (*GetEventAncestorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEventAncestors not implemented")
}
func (UnimplementedEventServiceServer) GetEventDescendants(context.Context, *GetEventDescendantsRequest) (*GetEventDescendantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEventDescendants not implemented")
}
func (UnimplementedEventServiceServer) MoveEvent(context.Context, *MoveEventRequest) (*MoveEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoveEvent not implemented")
}
func (UnimplementedEventServiceServer) SetEventEpoch(context.Context, *SetEventEpochRequest) (*SetEventEpochResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetEventEpoch not implemented")
}
func (UnimplementedEventServiceServer) GetEventEpoch(context.Context, *GetEventEpochRequest) (*GetEventEpochResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEventEpoch not implemented")
}
func (UnimplementedEventServiceServer) GetTimeline(context.Context, *GetTimelineRequest) (*GetTimelineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTimeline not implemented")
}
func (UnimplementedEventServiceServer) mustEmbedUnimplementedEventServiceServer() {}

// UnsafeEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventServiceServer will
// result in compilation errors.
type UnsafeEventServiceServer interface {
	mustEmbedUnimplementedEventServiceServer()
}

func RegisterEventServiceServer(s grpc.ServiceRegistrar, srv EventServiceServer) {
	s.RegisterService(&EventService_ServiceDesc, srv)
}

func _EventService_CreateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).CreateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_CreateEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).CreateEvent(ctx, req.(*CreateEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetEvent(ctx, req.(*GetEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_ListEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).ListEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_ListEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).ListEvents(ctx, req.(*ListEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_UpdateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).UpdateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_UpdateEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).UpdateEvent(ctx, req.(*UpdateEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_DeleteEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).DeleteEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_DeleteEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).DeleteEvent(ctx, req.(*DeleteEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_AddEventReference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddEventReferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).AddEventReference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_AddEventReference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).AddEventReference(ctx, req.(*AddEventReferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_RemoveEventReference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveEventReferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).RemoveEventReference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_RemoveEventReference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).RemoveEventReference(ctx, req.(*RemoveEventReferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetEventReferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventReferencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetEventReferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetEventReferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetEventReferences(ctx, req.(*GetEventReferencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_UpdateEventReference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEventReferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).UpdateEventReference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_UpdateEventReference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).UpdateEventReference(ctx, req.(*UpdateEventReferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetEventChildren_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventChildrenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetEventChildren(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetEventChildren_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetEventChildren(ctx, req.(*GetEventChildrenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetEventAncestors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventAncestorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetEventAncestors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetEventAncestors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetEventAncestors(ctx, req.(*GetEventAncestorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetEventDescendants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventDescendantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetEventDescendants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetEventDescendants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetEventDescendants(ctx, req.(*GetEventDescendantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_MoveEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).MoveEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_MoveEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).MoveEvent(ctx, req.(*MoveEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_SetEventEpoch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetEventEpochRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).SetEventEpoch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_SetEventEpoch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).SetEventEpoch(ctx, req.(*SetEventEpochRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetEventEpoch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventEpochRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetEventEpoch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetEventEpoch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetEventEpoch(ctx, req.(*GetEventEpochRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTimelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetTimeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetTimeline(ctx, req.(*GetTimelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventService_ServiceDesc is the grpc.ServiceDesc for EventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "event.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEvent",
			Handler:    _EventService_CreateEvent_Handler,
		},
		{
			MethodName: "GetEvent",
			Handler:    _EventService_GetEvent_Handler,
		},
		{
			MethodName: "ListEvents",
			Handler:    _EventService_ListEvents_Handler,
		},
		{
			MethodName: "UpdateEvent",
			Handler:    _EventService_UpdateEvent_Handler,
		},
		{
			MethodName: "DeleteEvent",
			Handler:    _EventService_DeleteEvent_Handler,
		},
		{
			MethodName: "AddEventReference",
			Handler:    _EventService_AddEventReference_Handler,
		},
		{
			MethodName: "RemoveEventReference",
			Handler:    _EventService_RemoveEventReference_Handler,
		},
		{
			MethodName: "GetEventReferences",
			Handler:    _EventService_GetEventReferences_Handler,
		},
		{
			MethodName: "UpdateEventReference",
			Handler:    _EventService_UpdateEventReference_Handler,
		},
		{
			MethodName: "GetEventChildren",
			Handler:    _EventService_GetEventChildren_Handler,
		},
		{
			MethodName: "GetEventAncestors",
			Handler:    _EventService_GetEventAncestors_Handler,
		},
		{
			MethodName: "GetEventDescendants",
			Handler:    _EventService_GetEventDescendants_Handler,
		},
		{
			MethodName: "MoveEvent",
			Handler:    _EventService_MoveEvent_Handler,
		},
		{
			MethodName: "SetEventEpoch",
			Handler:    _EventService_SetEventEpoch_Handler,
		},
		{
			MethodName: "GetEventEpoch",
			Handler:    _EventService_GetEventEpoch_Handler,
		},
		{
			MethodName: "GetTimeline",
			Handler:    _EventService_GetTimeline_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/event/event.proto",
}
