// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v6.33.2
// source: proto/archetype/archetype.proto

package archetype

import (
	common "github.com/story-engine/main-service/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Archetype represents an archetype entity
type Archetype struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId    string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name        string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Archetype) Reset() {
	*x = Archetype{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archetype_archetype_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Archetype) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Archetype) ProtoMessage() {}

func (x *Archetype) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archetype_archetype_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Archetype.ProtoReflect.Descriptor instead.
func (*Archetype) Descriptor() ([]byte, []int) {
	return file_proto_archetype_archetype_proto_rawDescGZIP(), []int{0}
}

func (x *Archetype) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Archetype) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Archetype) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Archetype) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Archetype) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Archetype) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateArchetypeRequest is the request to create a new archetype
type CreateArchetypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId    string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *CreateArchetypeRequest) Reset() {
	*x = CreateArchetypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archetype_archetype_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateArchetypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArchetypeRequest) ProtoMessage() {}

func (x *CreateArchetypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archetype_archetype_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArchetypeRequest.ProtoReflect.Descriptor instead.
func (*CreateArchetypeRequest) Descriptor() ([]byte, []int) {
	return file_proto_archetype_archetype_proto_rawDescGZIP(), []int{1}
}

func (x *CreateArchetypeRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateArchetypeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateArchetypeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// CreateArchetypeResponse is the response after creating an archetype
type CreateArchetypeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Archetype *Archetype `protobuf:"bytes,1,opt,name=archetype,proto3" json:"archetype,omitempty"`
}

func (x *CreateArchetypeResponse) Reset() {
	*x = CreateArchetypeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archetype_archetype_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateArchetypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArchetypeResponse) ProtoMessage() {}

func (x *CreateArchetypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archetype_archetype_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArchetypeResponse.ProtoReflect.Descriptor instead.
func (*CreateArchetypeResponse) Descriptor() ([]byte, []int) {
	return file_proto_archetype_archetype_proto_rawDescGZIP(), []int{2}
}

func (x *CreateArchetypeResponse) GetArchetype() *Archetype {
	if x != nil {
		return x.Archetype
	}
	return nil
}

// GetArchetypeRequest is the request to get an archetype by ID
type GetArchetypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetArchetypeRequest) Reset() {
	*x = GetArchetypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archetype_archetype_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetArchetypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArchetypeRequest) ProtoMessage() {}

func (x *GetArchetypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archetype_archetype_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArchetypeRequest.ProtoReflect.Descriptor instead.
func (*GetArchetypeRequest) Descriptor() ([]byte, []int) {
	return file_proto_archetype_archetype_proto_rawDescGZIP(), []int{3}
}

func (x *GetArchetypeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetArchetypeResponse is the response containing an archetype
type GetArchetypeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Archetype *Archetype `protobuf:"bytes,1,opt,name=archetype,proto3" json:"archetype,omitempty"`
}

func (x *GetArchetypeResponse) Reset() {
	*x = GetArchetypeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archetype_archetype_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetArchetypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArchetypeResponse) ProtoMessage() {}

func (x *GetArchetypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archetype_archetype_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArchetypeResponse.ProtoReflect.Descriptor instead.
func (*GetArchetypeResponse) Descriptor() ([]byte, []int) {
	return file_proto_archetype_archetype_proto_rawDescGZIP(), []int{4}
}

func (x *GetArchetypeResponse) GetArchetype() *Archetype {
	if x != nil {
		return x.Archetype
	}
	return nil
}

// ListArchetypesRequest is the request to list archetypes for a tenant
type ListArchetypesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId   string                    `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Pagination *common.PaginationRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (x *ListArchetypesRequest) Reset() {
	*x = ListArchetypesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archetype_archetype_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListArchetypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArchetypesRequest) ProtoMessage() {}

func (x *ListArchetypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archetype_archetype_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArchetypesRequest.ProtoReflect.Descriptor instead.
func (*ListArchetypesRequest) Descriptor() ([]byte, []int) {
	return file_proto_archetype_archetype_proto_rawDescGZIP(), []int{5}
}

func (x *ListArchetypesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListArchetypesRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// ListArchetypesResponse is the response containing a list of archetypes
type ListArchetypesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Archetypes []*Archetype `protobuf:"bytes,1,rep,name=archetypes,proto3" json:"archetypes,omitempty"`
	TotalCount int32        `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
}

func (x *ListArchetypesResponse) Reset() {
	*x = ListArchetypesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archetype_archetype_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListArchetypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArchetypesResponse) ProtoMessage() {}

func (x *ListArchetypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archetype_archetype_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArchetypesResponse.ProtoReflect.Descriptor instead.
func (*ListArchetypesResponse) Descriptor() ([]byte, []int) {
	return file_proto_archetype_archetype_proto_rawDescGZIP(), []int{6}
}

func (x *ListArchetypesResponse) GetArchetypes() []*Archetype {
	if x != nil {
		return x.Archetypes
	}
	return nil
}

func (x *ListArchetypesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// UpdateArchetypeRequest is the request to update an archetype
type UpdateArchetypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
}

func (x *UpdateArchetypeRequest) Reset() {
	*x = UpdateArchetypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archetype_archetype_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateArchetypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArchetypeRequest) ProtoMessage() {}

func (x *UpdateArchetypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archetype_archetype_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArchetypeRequest.ProtoReflect.Descriptor instead.
func (*UpdateArchetypeRequest) Descriptor() ([]byte, []int) {
	return file_proto_archetype_archetype_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateArchetypeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateArchetypeRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateArchetypeRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

// UpdateArchetypeResponse is the response after updating an archetype
type UpdateArchetypeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Archetype *Archetype `protobuf:"bytes,1,opt,name=archetype,proto3" json:"archetype,omitempty"`
}

func (x *UpdateArchetypeResponse) Reset() {
	*x = UpdateArchetypeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archetype_archetype_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateArchetypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArchetypeResponse) ProtoMessage() {}

func (x *UpdateArchetypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archetype_archetype_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArchetypeResponse.ProtoReflect.Descriptor instead.
func (*UpdateArchetypeResponse) Descriptor() ([]byte, []int) {
	return file_proto_archetype_archetype_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateArchetypeResponse) GetArchetype() *Archetype {
	if x != nil {
		return x.Archetype
	}
	return nil
}

// DeleteArchetypeRequest is the request to delete an archetype
type DeleteArchetypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteArchetypeRequest) Reset() {
	*x = DeleteArchetypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archetype_archetype_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteArchetypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArchetypeRequest) ProtoMessage() {}

func (x *DeleteArchetypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archetype_archetype_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArchetypeRequest.ProtoReflect.Descriptor instead.
func (*DeleteArchetypeRequest) Descriptor() ([]byte, []int) {
	return file_proto_archetype_archetype_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteArchetypeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteArchetypeResponse is the response after deleting an archetype
type DeleteArchetypeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteArchetypeResponse) Reset() {
	*x = DeleteArchetypeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archetype_archetype_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteArchetypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArchetypeResponse) ProtoMessage() {}

func (x *DeleteArchetypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archetype_archetype_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArchetypeResponse.ProtoReflect.Descriptor instead.
func (*DeleteArchetypeResponse) Descriptor() ([]byte, []int) {
	return file_proto_archetype_archetype_proto_rawDescGZIP(), []int{10}
}

// AddTraitToArchetypeRequest is the request to add a trait to an archetype
type AddTraitToArchetypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArchetypeId  string `protobuf:"bytes,1,opt,name=archetype_id,json=archetypeId,proto3" json:"archetype_id,omitempty"`
	TraitId      string `protobuf:"bytes,2,opt,name=trait_id,json=traitId,proto3" json:"trait_id,omitempty"`
	DefaultValue string `protobuf:"bytes,3,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
}

func (x *AddTraitToArchetypeRequest) Reset() {
	*x = AddTraitToArchetypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archetype_archetype_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTraitToArchetypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTraitToArchetypeRequest) ProtoMessage() {}

func (x *AddTraitToArchetypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archetype_archetype_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTraitToArchetypeRequest.ProtoReflect.Descriptor instead.
func (*AddTraitToArchetypeRequest) Descriptor() ([]byte, []int) {
	return file_proto_archetype_archetype_proto_rawDescGZIP(), []int{11}
}

func (x *AddTraitToArchetypeRequest) GetArchetypeId() string {
	if x != nil {
		return x.ArchetypeId
	}
	return ""
}

func (x *AddTraitToArchetypeRequest) GetTraitId() string {
	if x != nil {
		return x.TraitId
	}
	return ""
}

func (x *AddTraitToArchetypeRequest) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

// AddTraitToArchetypeResponse is the response after adding a trait
type AddTraitToArchetypeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddTraitToArchetypeResponse) Reset() {
	*x = AddTraitToArchetypeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archetype_archetype_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTraitToArchetypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTraitToArchetypeResponse) ProtoMessage() {}

func (x *AddTraitToArchetypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archetype_archetype_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTraitToArchetypeResponse.ProtoReflect.Descriptor instead.
func (*AddTraitToArchetypeResponse) Descriptor() ([]byte, []int) {
	return file_proto_archetype_archetype_proto_rawDescGZIP(), []int{12}
}

// RemoveTraitFromArchetypeRequest is the request to remove a trait from an archetype
type RemoveTraitFromArchetypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArchetypeId string `protobuf:"bytes,1,opt,name=archetype_id,json=archetypeId,proto3" json:"archetype_id,omitempty"`
	TraitId     string `protobuf:"bytes,2,opt,name=trait_id,json=traitId,proto3" json:"trait_id,omitempty"`
}

func (x *RemoveTraitFromArchetypeRequest) Reset() {
	*x = RemoveTraitFromArchetypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archetype_archetype_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveTraitFromArchetypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTraitFromArchetypeRequest) ProtoMessage() {}

func (x *RemoveTraitFromArchetypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archetype_archetype_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTraitFromArchetypeRequest.ProtoReflect.Descriptor instead.
func (*RemoveTraitFromArchetypeRequest) Descriptor() ([]byte, []int) {
	return file_proto_archetype_archetype_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveTraitFromArchetypeRequest) GetArchetypeId() string {
	if x != nil {
		return x.ArchetypeId
	}
	return ""
}

func (x *RemoveTraitFromArchetypeRequest) GetTraitId() string {
	if x != nil {
		return x.TraitId
	}
	return ""
}

// RemoveTraitFromArchetypeResponse is the response after removing a trait
type RemoveTraitFromArchetypeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveTraitFromArchetypeResponse) Reset() {
	*x = RemoveTraitFromArchetypeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archetype_archetype_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveTraitFromArchetypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTraitFromArchetypeResponse) ProtoMessage() {}

func (x *RemoveTraitFromArchetypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archetype_archetype_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTraitFromArchetypeResponse.ProtoReflect.Descriptor instead.
func (*RemoveTraitFromArchetypeResponse) Descriptor() ([]byte, []int) {
	return file_proto_archetype_archetype_proto_rawDescGZIP(), []int{14}
}

// ArchetypeTrait represents a trait assigned to an archetype
type ArchetypeTrait struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ArchetypeId      string                 `protobuf:"bytes,2,opt,name=archetype_id,json=archetypeId,proto3" json:"archetype_id,omitempty"`
	TraitId          string                 `protobuf:"bytes,3,opt,name=trait_id,json=traitId,proto3" json:"trait_id,omitempty"`
	TraitName        string                 `protobuf:"bytes,4,opt,name=trait_name,json=traitName,proto3" json:"trait_name,omitempty"`
	TraitCategory    string                 `protobuf:"bytes,5,opt,name=trait_category,json=traitCategory,proto3" json:"trait_category,omitempty"`
	TraitDescription string                 `protobuf:"bytes,6,opt,name=trait_description,json=traitDescription,proto3" json:"trait_description,omitempty"`
	DefaultValue     string                 `protobuf:"bytes,7,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *ArchetypeTrait) Reset() {
	*x = ArchetypeTrait{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archetype_archetype_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArchetypeTrait) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchetypeTrait) ProtoMessage() {}

func (x *ArchetypeTrait) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archetype_archetype_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchetypeTrait.ProtoReflect.Descriptor instead.
func (*ArchetypeTrait) Descriptor() ([]byte, []int) {
	return file_proto_archetype_archetype_proto_rawDescGZIP(), []int{15}
}

func (x *ArchetypeTrait) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ArchetypeTrait) GetArchetypeId() string {
	if x != nil {
		return x.ArchetypeId
	}
	return ""
}

func (x *ArchetypeTrait) GetTraitId() string {
	if x != nil {
		return x.TraitId
	}
	return ""
}

func (x *ArchetypeTrait) GetTraitName() string {
	if x != nil {
		return x.TraitName
	}
	return ""
}

func (x *ArchetypeTrait) GetTraitCategory() string {
	if x != nil {
		return x.TraitCategory
	}
	return ""
}

func (x *ArchetypeTrait) GetTraitDescription() string {
	if x != nil {
		return x.TraitDescription
	}
	return ""
}

func (x *ArchetypeTrait) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *ArchetypeTrait) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// GetArchetypeTraitsRequest is the request to get traits for an archetype
type GetArchetypeTraitsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArchetypeId string `protobuf:"bytes,1,opt,name=archetype_id,json=archetypeId,proto3" json:"archetype_id,omitempty"`
}

func (x *GetArchetypeTraitsRequest) Reset() {
	*x = GetArchetypeTraitsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archetype_archetype_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetArchetypeTraitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArchetypeTraitsRequest) ProtoMessage() {}

func (x *GetArchetypeTraitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archetype_archetype_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArchetypeTraitsRequest.ProtoReflect.Descriptor instead.
func (*GetArchetypeTraitsRequest) Descriptor() ([]byte, []int) {
	return file_proto_archetype_archetype_proto_rawDescGZIP(), []int{16}
}

func (x *GetArchetypeTraitsRequest) GetArchetypeId() string {
	if x != nil {
		return x.ArchetypeId
	}
	return ""
}

// GetArchetypeTraitsResponse is the response containing archetype traits
type GetArchetypeTraitsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Traits []*ArchetypeTrait `protobuf:"bytes,1,rep,name=traits,proto3" json:"traits,omitempty"`
}

func (x *GetArchetypeTraitsResponse) Reset() {
	*x = GetArchetypeTraitsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archetype_archetype_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetArchetypeTraitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArchetypeTraitsResponse) ProtoMessage() {}

func (x *GetArchetypeTraitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archetype_archetype_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArchetypeTraitsResponse.ProtoReflect.Descriptor instead.
func (*GetArchetypeTraitsResponse) Descriptor() ([]byte, []int) {
	return file_proto_archetype_archetype_proto_rawDescGZIP(), []int{17}
}

func (x *GetArchetypeTraitsResponse) GetTraits() []*ArchetypeTrait {
	if x != nil {
		return x.Traits
	}
	return nil
}

var File_proto_archetype_archetype_proto protoreflect.FileDescriptor

var file_proto_archetype_archetype_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70,
	0x65, 0x2f, 0x61, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x61, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe4, 0x01, 0x0a, 0x09, 0x41, 0x72, 0x63,
	0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22,
	0x6b, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79,
	0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e,
	0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65,
	0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4d, 0x0a, 0x17,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x61, 0x72, 0x63, 0x68, 0x65,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x72, 0x63,
	0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x41, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65,
	0x52, 0x09, 0x61, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x22, 0x25, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x41, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x4a, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79,
	0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x61, 0x72,
	0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x61, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x41, 0x72, 0x63, 0x68, 0x65, 0x74,
	0x79, 0x70, 0x65, 0x52, 0x09, 0x61, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x22, 0x6f,
	0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x6f, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x0a, 0x61, 0x72, 0x63,
	0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x61, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x41, 0x72, 0x63, 0x68, 0x65, 0x74,
	0x79, 0x70, 0x65, 0x52, 0x0a, 0x61, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x73, 0x12,
	0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x81, 0x01, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x63, 0x68, 0x65,
	0x74, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x88, 0x01, 0x01, 0x12, 0x25, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4d, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72,
	0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x32, 0x0a, 0x09, 0x61, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x41,
	0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x52, 0x09, 0x61, 0x72, 0x63, 0x68, 0x65, 0x74,
	0x79, 0x70, 0x65, 0x22, 0x28, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x72, 0x63,
	0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x19, 0x0a,
	0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x7f, 0x0a, 0x1a, 0x41, 0x64, 0x64, 0x54,
	0x72, 0x61, 0x69, 0x74, 0x54, 0x6f, 0x41, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x72, 0x63, 0x68, 0x65, 0x74,
	0x79, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x72,
	0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x72, 0x61,
	0x69, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61,
	0x69, 0x74, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1d, 0x0a, 0x1b, 0x41, 0x64, 0x64,
	0x54, 0x72, 0x61, 0x69, 0x74, 0x54, 0x6f, 0x41, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5f, 0x0a, 0x1f, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x54, 0x72, 0x61, 0x69, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x72, 0x63, 0x68, 0x65,
	0x74, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x61,
	0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x61, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x49, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x74, 0x72, 0x61, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x74, 0x72, 0x61, 0x69, 0x74, 0x49, 0x64, 0x22, 0x22, 0x0a, 0x20, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x54, 0x72, 0x61, 0x69, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x72, 0x63, 0x68,
	0x65, 0x74, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xb1, 0x02,
	0x0a, 0x0e, 0x41, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x54, 0x72, 0x61, 0x69, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x21, 0x0a, 0x0c, 0x61, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70,
	0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x69, 0x74, 0x49, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x74, 0x72, 0x61, 0x69, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x74, 0x72, 0x61, 0x69, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a,
	0x0e, 0x74, 0x72, 0x61, 0x69, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x74, 0x72, 0x61, 0x69, 0x74, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x12, 0x2b, 0x0a, 0x11, 0x74, 0x72, 0x61, 0x69, 0x74, 0x5f, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x10, 0x74, 0x72, 0x61, 0x69, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x22, 0x3e, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x41, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70,
	0x65, 0x54, 0x72, 0x61, 0x69, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21,
	0x0a, 0x0c, 0x61, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x49,
	0x64, 0x22, 0x4f, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x41, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70,
	0x65, 0x54, 0x72, 0x61, 0x69, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x31, 0x0a, 0x06, 0x74, 0x72, 0x61, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x61, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x41, 0x72, 0x63, 0x68,
	0x65, 0x74, 0x79, 0x70, 0x65, 0x54, 0x72, 0x61, 0x69, 0x74, 0x52, 0x06, 0x74, 0x72, 0x61, 0x69,
	0x74, 0x73, 0x32, 0x86, 0x06, 0x0a, 0x10, 0x41, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x58, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x41, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x12, 0x21, 0x2e, 0x61, 0x72, 0x63,
	0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x63,
	0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e,
	0x61, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x41, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x4f, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x41, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x1e, 0x2e, 0x61, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x58, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x63, 0x68,
	0x65, 0x74, 0x79, 0x70, 0x65, 0x12, 0x21, 0x2e, 0x61, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70,
	0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x72, 0x63, 0x68, 0x65,
	0x74, 0x79, 0x70, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x63, 0x68, 0x65,
	0x74, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x0e,
	0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x73, 0x12, 0x20,
	0x2e, 0x61, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41,
	0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x21, 0x2e, 0x61, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x41, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x72, 0x63,
	0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x12, 0x21, 0x2e, 0x61, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79,
	0x70, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79,
	0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x72, 0x63, 0x68,
	0x65, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x72, 0x63, 0x68,
	0x65, 0x74, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x61, 0x0a,
	0x12, 0x47, 0x65, 0x74, 0x41, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x54, 0x72, 0x61,
	0x69, 0x74, 0x73, 0x12, 0x24, 0x2e, 0x61, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x54, 0x72, 0x61, 0x69,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x61, 0x72, 0x63, 0x68,
	0x65, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79,
	0x70, 0x65, 0x54, 0x72, 0x61, 0x69, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x64, 0x0a, 0x13, 0x41, 0x64, 0x64, 0x54, 0x72, 0x61, 0x69, 0x74, 0x54, 0x6f, 0x41, 0x72,
	0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x12, 0x25, 0x2e, 0x61, 0x72, 0x63, 0x68, 0x65, 0x74,
	0x79, 0x70, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x72, 0x61, 0x69, 0x74, 0x54, 0x6f, 0x41, 0x72,
	0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26,
	0x2e, 0x61, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x72,
	0x61, 0x69, 0x74, 0x54, 0x6f, 0x41, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x73, 0x0a, 0x18, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x54, 0x72, 0x61, 0x69, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x2a, 0x2e, 0x61, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x72, 0x61, 0x69, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x72,
	0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b,
	0x2e, 0x61, 0x72, 0x63, 0x68, 0x65, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x54, 0x72, 0x61, 0x69, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x72, 0x63, 0x68, 0x65, 0x74,
	0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x36, 0x5a, 0x34, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2d,
	0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x6d, 0x61, 0x69, 0x6e, 0x2d, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x72, 0x63, 0x68, 0x65, 0x74,
	0x79, 0x70, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_archetype_archetype_proto_rawDescOnce sync.Once
	file_proto_archetype_archetype_proto_rawDescData = file_proto_archetype_archetype_proto_rawDesc
)

func file_proto_archetype_archetype_proto_rawDescGZIP() []byte {
	file_proto_archetype_archetype_proto_rawDescOnce.Do(func() {
		file_proto_archetype_archetype_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_archetype_archetype_proto_rawDescData)
	})
	return file_proto_archetype_archetype_proto_rawDescData
}

var file_proto_archetype_archetype_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_archetype_archetype_proto_goTypes = []interface{}{
	(*Archetype)(nil),                        // 0: archetype.Archetype
	(*CreateArchetypeRequest)(nil),           // 1: archetype.CreateArchetypeRequest
	(*CreateArchetypeResponse)(nil),          // 2: archetype.CreateArchetypeResponse
	(*GetArchetypeRequest)(nil),              // 3: archetype.GetArchetypeRequest
	(*GetArchetypeResponse)(nil),             // 4: archetype.GetArchetypeResponse
	(*ListArchetypesRequest)(nil),            // 5: archetype.ListArchetypesRequest
	(*ListArchetypesResponse)(nil),           // 6: archetype.ListArchetypesResponse
	(*UpdateArchetypeRequest)(nil),           // 7: archetype.UpdateArchetypeRequest
	(*UpdateArchetypeResponse)(nil),          // 8: archetype.UpdateArchetypeResponse
	(*DeleteArchetypeRequest)(nil),           // 9: archetype.DeleteArchetypeRequest
	(*DeleteArchetypeResponse)(nil),          // 10: archetype.DeleteArchetypeResponse
	(*AddTraitToArchetypeRequest)(nil),       // 11: archetype.AddTraitToArchetypeRequest
	(*AddTraitToArchetypeResponse)(nil),      // 12: archetype.AddTraitToArchetypeResponse
	(*RemoveTraitFromArchetypeRequest)(nil),  // 13: archetype.RemoveTraitFromArchetypeRequest
	(*RemoveTraitFromArchetypeResponse)(nil), // 14: archetype.RemoveTraitFromArchetypeResponse
	(*ArchetypeTrait)(nil),                   // 15: archetype.ArchetypeTrait
	(*GetArchetypeTraitsRequest)(nil),        // 16: archetype.GetArchetypeTraitsRequest
	(*GetArchetypeTraitsResponse)(nil),       // 17: archetype.GetArchetypeTraitsResponse
	(*timestamppb.Timestamp)(nil),            // 18: google.protobuf.Timestamp
	(*common.PaginationRequest)(nil),         // 19: common.PaginationRequest
}
var file_proto_archetype_archetype_proto_depIdxs = []int32{
	18, // 0: archetype.Archetype.created_at:type_name -> google.protobuf.Timestamp
	18, // 1: archetype.Archetype.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: archetype.CreateArchetypeResponse.archetype:type_name -> archetype.Archetype
	0,  // 3: archetype.GetArchetypeResponse.archetype:type_name -> archetype.Archetype
	19, // 4: archetype.ListArchetypesRequest.pagination:type_name -> common.PaginationRequest
	0,  // 5: archetype.ListArchetypesResponse.archetypes:type_name -> archetype.Archetype
	0,  // 6: archetype.UpdateArchetypeResponse.archetype:type_name -> archetype.Archetype
	18, // 7: archetype.ArchetypeTrait.created_at:type_name -> google.protobuf.Timestamp
	15, // 8: archetype.GetArchetypeTraitsResponse.traits:type_name -> archetype.ArchetypeTrait
	1,  // 9: archetype.ArchetypeService.CreateArchetype:input_type -> archetype.CreateArchetypeRequest
	3,  // 10: archetype.ArchetypeService.GetArchetype:input_type -> archetype.GetArchetypeRequest
	7,  // 11: archetype.ArchetypeService.UpdateArchetype:input_type -> archetype.UpdateArchetypeRequest
	5,  // 12: archetype.ArchetypeService.ListArchetypes:input_type -> archetype.ListArchetypesRequest
	9,  // 13: archetype.ArchetypeService.DeleteArchetype:input_type -> archetype.DeleteArchetypeRequest
	16, // 14: archetype.ArchetypeService.GetArchetypeTraits:input_type -> archetype.GetArchetypeTraitsRequest
	11, // 15: archetype.ArchetypeService.AddTraitToArchetype:input_type -> archetype.AddTraitToArchetypeRequest
	13, // 16: archetype.ArchetypeService.RemoveTraitFromArchetype:input_type -> archetype.RemoveTraitFromArchetypeRequest
	2,  // 17: archetype.ArchetypeService.CreateArchetype:output_type -> archetype.CreateArchetypeResponse
	4,  // 18: archetype.ArchetypeService.GetArchetype:output_type -> archetype.GetArchetypeResponse
	8,  // 19: archetype.ArchetypeService.UpdateArchetype:output_type -> archetype.UpdateArchetypeResponse
	6,  // 20: archetype.ArchetypeService.ListArchetypes:output_type -> archetype.ListArchetypesResponse
	10, // 21: archetype.ArchetypeService.DeleteArchetype:output_type -> archetype.DeleteArchetypeResponse
	17, // 22: archetype.ArchetypeService.GetArchetypeTraits:output_type -> archetype.GetArchetypeTraitsResponse
	12, // 23: archetype.ArchetypeService.AddTraitToArchetype:output_type -> archetype.AddTraitToArchetypeResponse
	14, // 24: archetype.ArchetypeService.RemoveTraitFromArchetype:output_type -> archetype.RemoveTraitFromArchetypeResponse
	17, // [17:25] is the sub-list for method output_type
	9,  // [9:17] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_archetype_archetype_proto_init() }
func file_proto_archetype_archetype_proto_init() {
	if File_proto_archetype_archetype_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_archetype_archetype_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Archetype); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archetype_archetype_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateArchetypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archetype_archetype_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateArchetypeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archetype_archetype_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetArchetypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archetype_archetype_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetArchetypeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archetype_archetype_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListArchetypesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archetype_archetype_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListArchetypesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archetype_archetype_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateArchetypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archetype_archetype_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateArchetypeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archetype_archetype_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteArchetypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archetype_archetype_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteArchetypeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archetype_archetype_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTraitToArchetypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archetype_archetype_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTraitToArchetypeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archetype_archetype_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveTraitFromArchetypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archetype_archetype_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveTraitFromArchetypeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archetype_archetype_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArchetypeTrait); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archetype_archetype_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetArchetypeTraitsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archetype_archetype_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetArchetypeTraitsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_archetype_archetype_proto_msgTypes[7].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_archetype_archetype_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_archetype_archetype_proto_goTypes,
		DependencyIndexes: file_proto_archetype_archetype_proto_depIdxs,
		MessageInfos:      file_proto_archetype_archetype_proto_msgTypes,
	}.Build()
	File_proto_archetype_archetype_proto = out.File
	file_proto_archetype_archetype_proto_rawDesc = nil
	file_proto_archetype_archetype_proto_goTypes = nil
	file_proto_archetype_archetype_proto_depIdxs = nil
}
