// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.2
// source: proto/character_skill/character_skill.proto

package character_skill

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CharacterSkillService_AddCharacterSkill_FullMethodName    = "/character_skill.CharacterSkillService/AddCharacterSkill"
	CharacterSkillService_UpdateCharacterSkill_FullMethodName = "/character_skill.CharacterSkillService/UpdateCharacterSkill"
	CharacterSkillService_RemoveCharacterSkill_FullMethodName = "/character_skill.CharacterSkillService/RemoveCharacterSkill"
	CharacterSkillService_ListCharacterSkills_FullMethodName  = "/character_skill.CharacterSkillService/ListCharacterSkills"
)

// CharacterSkillServiceClient is the client API for CharacterSkillService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CharacterSkillServiceClient interface {
	// AddCharacterSkill adds a skill to a character
	AddCharacterSkill(ctx context.Context, in *AddCharacterSkillRequest, opts ...grpc.CallOption) (*AddCharacterSkillResponse, error)
	// UpdateCharacterSkill updates a character's skill
	UpdateCharacterSkill(ctx context.Context, in *UpdateCharacterSkillRequest, opts ...grpc.CallOption) (*UpdateCharacterSkillResponse, error)
	// RemoveCharacterSkill removes a skill from a character
	RemoveCharacterSkill(ctx context.Context, in *RemoveCharacterSkillRequest, opts ...grpc.CallOption) (*RemoveCharacterSkillResponse, error)
	// ListCharacterSkills lists skills for a character with pagination
	ListCharacterSkills(ctx context.Context, in *ListCharacterSkillsRequest, opts ...grpc.CallOption) (*ListCharacterSkillsResponse, error)
}

type characterSkillServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCharacterSkillServiceClient(cc grpc.ClientConnInterface) CharacterSkillServiceClient {
	return &characterSkillServiceClient{cc}
}

func (c *characterSkillServiceClient) AddCharacterSkill(ctx context.Context, in *AddCharacterSkillRequest, opts ...grpc.CallOption) (*AddCharacterSkillResponse, error) {
	out := new(AddCharacterSkillResponse)
	err := c.cc.Invoke(ctx, CharacterSkillService_AddCharacterSkill_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *characterSkillServiceClient) UpdateCharacterSkill(ctx context.Context, in *UpdateCharacterSkillRequest, opts ...grpc.CallOption) (*UpdateCharacterSkillResponse, error) {
	out := new(UpdateCharacterSkillResponse)
	err := c.cc.Invoke(ctx, CharacterSkillService_UpdateCharacterSkill_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *characterSkillServiceClient) RemoveCharacterSkill(ctx context.Context, in *RemoveCharacterSkillRequest, opts ...grpc.CallOption) (*RemoveCharacterSkillResponse, error) {
	out := new(RemoveCharacterSkillResponse)
	err := c.cc.Invoke(ctx, CharacterSkillService_RemoveCharacterSkill_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *characterSkillServiceClient) ListCharacterSkills(ctx context.Context, in *ListCharacterSkillsRequest, opts ...grpc.CallOption) (*ListCharacterSkillsResponse, error) {
	out := new(ListCharacterSkillsResponse)
	err := c.cc.Invoke(ctx, CharacterSkillService_ListCharacterSkills_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CharacterSkillServiceServer is the server API for CharacterSkillService service.
// All implementations must embed UnimplementedCharacterSkillServiceServer
// for forward compatibility
type CharacterSkillServiceServer interface {
	// AddCharacterSkill adds a skill to a character
	AddCharacterSkill(context.Context, *AddCharacterSkillRequest) (*AddCharacterSkillResponse, error)
	// UpdateCharacterSkill updates a character's skill
	UpdateCharacterSkill(context.Context, *UpdateCharacterSkillRequest) (*UpdateCharacterSkillResponse, error)
	// RemoveCharacterSkill removes a skill from a character
	RemoveCharacterSkill(context.Context, *RemoveCharacterSkillRequest) (*RemoveCharacterSkillResponse, error)
	// ListCharacterSkills lists skills for a character with pagination
	ListCharacterSkills(context.Context, *ListCharacterSkillsRequest) (*ListCharacterSkillsResponse, error)
	mustEmbedUnimplementedCharacterSkillServiceServer()
}

// UnimplementedCharacterSkillServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCharacterSkillServiceServer struct {
}

func (UnimplementedCharacterSkillServiceServer) AddCharacterSkill(context.Context, *AddCharacterSkillRequest) (*AddCharacterSkillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCharacterSkill not implemented")
}
func (UnimplementedCharacterSkillServiceServer) UpdateCharacterSkill(context.Context, *UpdateCharacterSkillRequest) (*UpdateCharacterSkillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCharacterSkill not implemented")
}
func (UnimplementedCharacterSkillServiceServer) RemoveCharacterSkill(context.Context, *RemoveCharacterSkillRequest) (*RemoveCharacterSkillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveCharacterSkill not implemented")
}
func (UnimplementedCharacterSkillServiceServer) ListCharacterSkills(context.Context, *ListCharacterSkillsRequest) (*ListCharacterSkillsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCharacterSkills not implemented")
}
func (UnimplementedCharacterSkillServiceServer) mustEmbedUnimplementedCharacterSkillServiceServer() {}

// UnsafeCharacterSkillServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CharacterSkillServiceServer will
// result in compilation errors.
type UnsafeCharacterSkillServiceServer interface {
	mustEmbedUnimplementedCharacterSkillServiceServer()
}

func RegisterCharacterSkillServiceServer(s grpc.ServiceRegistrar, srv CharacterSkillServiceServer) {
	s.RegisterService(&CharacterSkillService_ServiceDesc, srv)
}

func _CharacterSkillService_AddCharacterSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCharacterSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CharacterSkillServiceServer).AddCharacterSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CharacterSkillService_AddCharacterSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CharacterSkillServiceServer).AddCharacterSkill(ctx, req.(*AddCharacterSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CharacterSkillService_UpdateCharacterSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCharacterSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CharacterSkillServiceServer).UpdateCharacterSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CharacterSkillService_UpdateCharacterSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CharacterSkillServiceServer).UpdateCharacterSkill(ctx, req.(*UpdateCharacterSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CharacterSkillService_RemoveCharacterSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveCharacterSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CharacterSkillServiceServer).RemoveCharacterSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CharacterSkillService_RemoveCharacterSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CharacterSkillServiceServer).RemoveCharacterSkill(ctx, req.(*RemoveCharacterSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CharacterSkillService_ListCharacterSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCharacterSkillsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CharacterSkillServiceServer).ListCharacterSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CharacterSkillService_ListCharacterSkills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CharacterSkillServiceServer).ListCharacterSkills(ctx, req.(*ListCharacterSkillsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CharacterSkillService_ServiceDesc is the grpc.ServiceDesc for CharacterSkillService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CharacterSkillService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "character_skill.CharacterSkillService",
	HandlerType: (*CharacterSkillServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddCharacterSkill",
			Handler:    _CharacterSkillService_AddCharacterSkill_Handler,
		},
		{
			MethodName: "UpdateCharacterSkill",
			Handler:    _CharacterSkillService_UpdateCharacterSkill_Handler,
		},
		{
			MethodName: "RemoveCharacterSkill",
			Handler:    _CharacterSkillService_RemoveCharacterSkill_Handler,
		},
		{
			MethodName: "ListCharacterSkills",
			Handler:    _CharacterSkillService_ListCharacterSkills_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/character_skill/character_skill.proto",
}
