// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v6.33.2
// source: proto/prose/prose.proto

package prose

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProseBlock represents a block of prose text
type ProseBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChapterId *string                `protobuf:"bytes,2,opt,name=chapter_id,json=chapterId,proto3,oneof" json:"chapter_id,omitempty"`
	OrderNum  *int32                 `protobuf:"varint,3,opt,name=order_num,json=orderNum,proto3,oneof" json:"order_num,omitempty"`
	Kind      string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"` // final, alt_a, alt_b, cleaned, localized, draft
	Content   string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	WordCount int32                  `protobuf:"varint,6,opt,name=word_count,json=wordCount,proto3" json:"word_count,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *ProseBlock) Reset() {
	*x = ProseBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_prose_prose_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProseBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProseBlock) ProtoMessage() {}

func (x *ProseBlock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prose_prose_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProseBlock.ProtoReflect.Descriptor instead.
func (*ProseBlock) Descriptor() ([]byte, []int) {
	return file_proto_prose_prose_proto_rawDescGZIP(), []int{0}
}

func (x *ProseBlock) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProseBlock) GetChapterId() string {
	if x != nil && x.ChapterId != nil {
		return *x.ChapterId
	}
	return ""
}

func (x *ProseBlock) GetOrderNum() int32 {
	if x != nil && x.OrderNum != nil {
		return *x.OrderNum
	}
	return 0
}

func (x *ProseBlock) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ProseBlock) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ProseBlock) GetWordCount() int32 {
	if x != nil {
		return x.WordCount
	}
	return 0
}

func (x *ProseBlock) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProseBlock) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ProseBlockReference represents a reference from an entity to a prose block
type ProseBlockReference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProseBlockId string                 `protobuf:"bytes,2,opt,name=prose_block_id,json=proseBlockId,proto3" json:"prose_block_id,omitempty"`
	EntityType   string                 `protobuf:"bytes,3,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"` // scene, beat, chapter, character, location, artifact, event, world
	EntityId     string                 `protobuf:"bytes,4,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	CreatedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *ProseBlockReference) Reset() {
	*x = ProseBlockReference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_prose_prose_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProseBlockReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProseBlockReference) ProtoMessage() {}

func (x *ProseBlockReference) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prose_prose_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProseBlockReference.ProtoReflect.Descriptor instead.
func (*ProseBlockReference) Descriptor() ([]byte, []int) {
	return file_proto_prose_prose_proto_rawDescGZIP(), []int{1}
}

func (x *ProseBlockReference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProseBlockReference) GetProseBlockId() string {
	if x != nil {
		return x.ProseBlockId
	}
	return ""
}

func (x *ProseBlockReference) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *ProseBlockReference) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *ProseBlockReference) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// CreateProseBlockRequest is the request to create a new prose block
type CreateProseBlockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChapterId *string `protobuf:"bytes,1,opt,name=chapter_id,json=chapterId,proto3,oneof" json:"chapter_id,omitempty"`
	OrderNum  *int32  `protobuf:"varint,2,opt,name=order_num,json=orderNum,proto3,oneof" json:"order_num,omitempty"`
	Kind      string  `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Content   string  `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *CreateProseBlockRequest) Reset() {
	*x = CreateProseBlockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_prose_prose_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateProseBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProseBlockRequest) ProtoMessage() {}

func (x *CreateProseBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prose_prose_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProseBlockRequest.ProtoReflect.Descriptor instead.
func (*CreateProseBlockRequest) Descriptor() ([]byte, []int) {
	return file_proto_prose_prose_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProseBlockRequest) GetChapterId() string {
	if x != nil && x.ChapterId != nil {
		return *x.ChapterId
	}
	return ""
}

func (x *CreateProseBlockRequest) GetOrderNum() int32 {
	if x != nil && x.OrderNum != nil {
		return *x.OrderNum
	}
	return 0
}

func (x *CreateProseBlockRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CreateProseBlockRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// CreateProseBlockResponse is the response after creating a prose block
type CreateProseBlockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProseBlock *ProseBlock `protobuf:"bytes,1,opt,name=prose_block,json=proseBlock,proto3" json:"prose_block,omitempty"`
}

func (x *CreateProseBlockResponse) Reset() {
	*x = CreateProseBlockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_prose_prose_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateProseBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProseBlockResponse) ProtoMessage() {}

func (x *CreateProseBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prose_prose_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProseBlockResponse.ProtoReflect.Descriptor instead.
func (*CreateProseBlockResponse) Descriptor() ([]byte, []int) {
	return file_proto_prose_prose_proto_rawDescGZIP(), []int{3}
}

func (x *CreateProseBlockResponse) GetProseBlock() *ProseBlock {
	if x != nil {
		return x.ProseBlock
	}
	return nil
}

// GetProseBlockRequest is the request to get a prose block by ID
type GetProseBlockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetProseBlockRequest) Reset() {
	*x = GetProseBlockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_prose_prose_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProseBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProseBlockRequest) ProtoMessage() {}

func (x *GetProseBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prose_prose_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProseBlockRequest.ProtoReflect.Descriptor instead.
func (*GetProseBlockRequest) Descriptor() ([]byte, []int) {
	return file_proto_prose_prose_proto_rawDescGZIP(), []int{4}
}

func (x *GetProseBlockRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetProseBlockResponse is the response containing a prose block
type GetProseBlockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProseBlock *ProseBlock `protobuf:"bytes,1,opt,name=prose_block,json=proseBlock,proto3" json:"prose_block,omitempty"`
}

func (x *GetProseBlockResponse) Reset() {
	*x = GetProseBlockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_prose_prose_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProseBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProseBlockResponse) ProtoMessage() {}

func (x *GetProseBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prose_prose_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProseBlockResponse.ProtoReflect.Descriptor instead.
func (*GetProseBlockResponse) Descriptor() ([]byte, []int) {
	return file_proto_prose_prose_proto_rawDescGZIP(), []int{5}
}

func (x *GetProseBlockResponse) GetProseBlock() *ProseBlock {
	if x != nil {
		return x.ProseBlock
	}
	return nil
}

// UpdateProseBlockRequest is the request to update a prose block
type UpdateProseBlockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNum *int32  `protobuf:"varint,2,opt,name=order_num,json=orderNum,proto3,oneof" json:"order_num,omitempty"`
	Kind     *string `protobuf:"bytes,3,opt,name=kind,proto3,oneof" json:"kind,omitempty"`
	Content  *string `protobuf:"bytes,4,opt,name=content,proto3,oneof" json:"content,omitempty"`
}

func (x *UpdateProseBlockRequest) Reset() {
	*x = UpdateProseBlockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_prose_prose_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateProseBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProseBlockRequest) ProtoMessage() {}

func (x *UpdateProseBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prose_prose_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProseBlockRequest.ProtoReflect.Descriptor instead.
func (*UpdateProseBlockRequest) Descriptor() ([]byte, []int) {
	return file_proto_prose_prose_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateProseBlockRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProseBlockRequest) GetOrderNum() int32 {
	if x != nil && x.OrderNum != nil {
		return *x.OrderNum
	}
	return 0
}

func (x *UpdateProseBlockRequest) GetKind() string {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return ""
}

func (x *UpdateProseBlockRequest) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

// UpdateProseBlockResponse is the response after updating a prose block
type UpdateProseBlockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProseBlock *ProseBlock `protobuf:"bytes,1,opt,name=prose_block,json=proseBlock,proto3" json:"prose_block,omitempty"`
}

func (x *UpdateProseBlockResponse) Reset() {
	*x = UpdateProseBlockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_prose_prose_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateProseBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProseBlockResponse) ProtoMessage() {}

func (x *UpdateProseBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prose_prose_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProseBlockResponse.ProtoReflect.Descriptor instead.
func (*UpdateProseBlockResponse) Descriptor() ([]byte, []int) {
	return file_proto_prose_prose_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateProseBlockResponse) GetProseBlock() *ProseBlock {
	if x != nil {
		return x.ProseBlock
	}
	return nil
}

// DeleteProseBlockRequest is the request to delete a prose block
type DeleteProseBlockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteProseBlockRequest) Reset() {
	*x = DeleteProseBlockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_prose_prose_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteProseBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProseBlockRequest) ProtoMessage() {}

func (x *DeleteProseBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prose_prose_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProseBlockRequest.ProtoReflect.Descriptor instead.
func (*DeleteProseBlockRequest) Descriptor() ([]byte, []int) {
	return file_proto_prose_prose_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteProseBlockRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteProseBlockResponse is the response after deleting a prose block
type DeleteProseBlockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteProseBlockResponse) Reset() {
	*x = DeleteProseBlockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_prose_prose_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteProseBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProseBlockResponse) ProtoMessage() {}

func (x *DeleteProseBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prose_prose_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProseBlockResponse.ProtoReflect.Descriptor instead.
func (*DeleteProseBlockResponse) Descriptor() ([]byte, []int) {
	return file_proto_prose_prose_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteProseBlockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ListProseBlocksByChapterRequest is the request to list prose blocks for a chapter
type ListProseBlocksByChapterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChapterId string `protobuf:"bytes,1,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
}

func (x *ListProseBlocksByChapterRequest) Reset() {
	*x = ListProseBlocksByChapterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_prose_prose_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListProseBlocksByChapterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProseBlocksByChapterRequest) ProtoMessage() {}

func (x *ListProseBlocksByChapterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prose_prose_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProseBlocksByChapterRequest.ProtoReflect.Descriptor instead.
func (*ListProseBlocksByChapterRequest) Descriptor() ([]byte, []int) {
	return file_proto_prose_prose_proto_rawDescGZIP(), []int{10}
}

func (x *ListProseBlocksByChapterRequest) GetChapterId() string {
	if x != nil {
		return x.ChapterId
	}
	return ""
}

// ListProseBlocksByChapterResponse is the response containing prose blocks
type ListProseBlocksByChapterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProseBlocks []*ProseBlock `protobuf:"bytes,1,rep,name=prose_blocks,json=proseBlocks,proto3" json:"prose_blocks,omitempty"`
	TotalCount  int32         `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
}

func (x *ListProseBlocksByChapterResponse) Reset() {
	*x = ListProseBlocksByChapterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_prose_prose_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListProseBlocksByChapterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProseBlocksByChapterResponse) ProtoMessage() {}

func (x *ListProseBlocksByChapterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prose_prose_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProseBlocksByChapterResponse.ProtoReflect.Descriptor instead.
func (*ListProseBlocksByChapterResponse) Descriptor() ([]byte, []int) {
	return file_proto_prose_prose_proto_rawDescGZIP(), []int{11}
}

func (x *ListProseBlocksByChapterResponse) GetProseBlocks() []*ProseBlock {
	if x != nil {
		return x.ProseBlocks
	}
	return nil
}

func (x *ListProseBlocksByChapterResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// CreateProseBlockReferenceRequest is the request to create a reference
type CreateProseBlockReferenceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProseBlockId string `protobuf:"bytes,1,opt,name=prose_block_id,json=proseBlockId,proto3" json:"prose_block_id,omitempty"`
	EntityType   string `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId     string `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
}

func (x *CreateProseBlockReferenceRequest) Reset() {
	*x = CreateProseBlockReferenceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_prose_prose_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateProseBlockReferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProseBlockReferenceRequest) ProtoMessage() {}

func (x *CreateProseBlockReferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prose_prose_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProseBlockReferenceRequest.ProtoReflect.Descriptor instead.
func (*CreateProseBlockReferenceRequest) Descriptor() ([]byte, []int) {
	return file_proto_prose_prose_proto_rawDescGZIP(), []int{12}
}

func (x *CreateProseBlockReferenceRequest) GetProseBlockId() string {
	if x != nil {
		return x.ProseBlockId
	}
	return ""
}

func (x *CreateProseBlockReferenceRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *CreateProseBlockReferenceRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

// CreateProseBlockReferenceResponse is the response after creating a reference
type CreateProseBlockReferenceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reference *ProseBlockReference `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
}

func (x *CreateProseBlockReferenceResponse) Reset() {
	*x = CreateProseBlockReferenceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_prose_prose_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateProseBlockReferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProseBlockReferenceResponse) ProtoMessage() {}

func (x *CreateProseBlockReferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prose_prose_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProseBlockReferenceResponse.ProtoReflect.Descriptor instead.
func (*CreateProseBlockReferenceResponse) Descriptor() ([]byte, []int) {
	return file_proto_prose_prose_proto_rawDescGZIP(), []int{13}
}

func (x *CreateProseBlockReferenceResponse) GetReference() *ProseBlockReference {
	if x != nil {
		return x.Reference
	}
	return nil
}

// ListProseBlockReferencesByProseBlockRequest lists references for a prose block
type ListProseBlockReferencesByProseBlockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProseBlockId string `protobuf:"bytes,1,opt,name=prose_block_id,json=proseBlockId,proto3" json:"prose_block_id,omitempty"`
}

func (x *ListProseBlockReferencesByProseBlockRequest) Reset() {
	*x = ListProseBlockReferencesByProseBlockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_prose_prose_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListProseBlockReferencesByProseBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProseBlockReferencesByProseBlockRequest) ProtoMessage() {}

func (x *ListProseBlockReferencesByProseBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prose_prose_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProseBlockReferencesByProseBlockRequest.ProtoReflect.Descriptor instead.
func (*ListProseBlockReferencesByProseBlockRequest) Descriptor() ([]byte, []int) {
	return file_proto_prose_prose_proto_rawDescGZIP(), []int{14}
}

func (x *ListProseBlockReferencesByProseBlockRequest) GetProseBlockId() string {
	if x != nil {
		return x.ProseBlockId
	}
	return ""
}

// ListProseBlockReferencesByProseBlockResponse contains references for a prose block
type ListProseBlockReferencesByProseBlockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	References []*ProseBlockReference `protobuf:"bytes,1,rep,name=references,proto3" json:"references,omitempty"`
	TotalCount int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
}

func (x *ListProseBlockReferencesByProseBlockResponse) Reset() {
	*x = ListProseBlockReferencesByProseBlockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_prose_prose_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListProseBlockReferencesByProseBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProseBlockReferencesByProseBlockResponse) ProtoMessage() {}

func (x *ListProseBlockReferencesByProseBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prose_prose_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProseBlockReferencesByProseBlockResponse.ProtoReflect.Descriptor instead.
func (*ListProseBlockReferencesByProseBlockResponse) Descriptor() ([]byte, []int) {
	return file_proto_prose_prose_proto_rawDescGZIP(), []int{15}
}

func (x *ListProseBlockReferencesByProseBlockResponse) GetReferences() []*ProseBlockReference {
	if x != nil {
		return x.References
	}
	return nil
}

func (x *ListProseBlockReferencesByProseBlockResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// ListProseBlocksByEntityRequest lists prose blocks for an entity
type ListProseBlocksByEntityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityType string `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId   string `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
}

func (x *ListProseBlocksByEntityRequest) Reset() {
	*x = ListProseBlocksByEntityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_prose_prose_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListProseBlocksByEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProseBlocksByEntityRequest) ProtoMessage() {}

func (x *ListProseBlocksByEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prose_prose_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProseBlocksByEntityRequest.ProtoReflect.Descriptor instead.
func (*ListProseBlocksByEntityRequest) Descriptor() ([]byte, []int) {
	return file_proto_prose_prose_proto_rawDescGZIP(), []int{16}
}

func (x *ListProseBlocksByEntityRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *ListProseBlocksByEntityRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

// ListProseBlocksByEntityResponse contains prose blocks for an entity
type ListProseBlocksByEntityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProseBlocks []*ProseBlock `protobuf:"bytes,1,rep,name=prose_blocks,json=proseBlocks,proto3" json:"prose_blocks,omitempty"`
	TotalCount  int32         `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
}

func (x *ListProseBlocksByEntityResponse) Reset() {
	*x = ListProseBlocksByEntityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_prose_prose_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListProseBlocksByEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProseBlocksByEntityResponse) ProtoMessage() {}

func (x *ListProseBlocksByEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prose_prose_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProseBlocksByEntityResponse.ProtoReflect.Descriptor instead.
func (*ListProseBlocksByEntityResponse) Descriptor() ([]byte, []int) {
	return file_proto_prose_prose_proto_rawDescGZIP(), []int{17}
}

func (x *ListProseBlocksByEntityResponse) GetProseBlocks() []*ProseBlock {
	if x != nil {
		return x.ProseBlocks
	}
	return nil
}

func (x *ListProseBlocksByEntityResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// DeleteProseBlockReferenceRequest is the request to delete a reference
type DeleteProseBlockReferenceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteProseBlockReferenceRequest) Reset() {
	*x = DeleteProseBlockReferenceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_prose_prose_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteProseBlockReferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProseBlockReferenceRequest) ProtoMessage() {}

func (x *DeleteProseBlockReferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prose_prose_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProseBlockReferenceRequest.ProtoReflect.Descriptor instead.
func (*DeleteProseBlockReferenceRequest) Descriptor() ([]byte, []int) {
	return file_proto_prose_prose_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteProseBlockReferenceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteProseBlockReferenceResponse is the response after deleting a reference
type DeleteProseBlockReferenceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteProseBlockReferenceResponse) Reset() {
	*x = DeleteProseBlockReferenceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_prose_prose_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteProseBlockReferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProseBlockReferenceResponse) ProtoMessage() {}

func (x *DeleteProseBlockReferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prose_prose_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProseBlockReferenceResponse.ProtoReflect.Descriptor instead.
func (*DeleteProseBlockReferenceResponse) Descriptor() ([]byte, []int) {
	return file_proto_prose_prose_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteProseBlockReferenceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_prose_prose_proto protoreflect.FileDescriptor

var file_proto_prose_prose_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x73, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x73, 0x65,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xc2, 0x02, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x22, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x49,
	0x64, 0x88, 0x01, 0x01, 0x12, 0x20, 0x0a, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x75,
	0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x4e, 0x75, 0x6d, 0x88, 0x01, 0x01, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x77, 0x6f, 0x72, 0x64, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39,
	0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x63, 0x68,
	0x61, 0x70, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x5f, 0x6e, 0x75, 0x6d, 0x22, 0xc4, 0x01, 0x0a, 0x13, 0x50, 0x72, 0x6f, 0x73, 0x65,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x24,
	0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x73, 0x65, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x49, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xaa, 0x01,
	0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0a, 0x63, 0x68, 0x61,
	0x70, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x09, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x20, 0x0a,
	0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x48, 0x01, 0x52, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x88, 0x01, 0x01, 0x12,
	0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b,
	0x69, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x0d, 0x0a,
	0x0b, 0x5f, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x42, 0x0c, 0x0a, 0x0a,
	0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x75, 0x6d, 0x22, 0x4e, 0x0a, 0x18, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x73, 0x65, 0x5f,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72,
	0x6f, 0x73, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x0a,
	0x70, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x26, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x4b, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x0b, 0x70,
	0x72, 0x6f, 0x73, 0x65, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x73, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x22,
	0xa6, 0x01, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x09, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00,
	0x52, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a,
	0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x04, 0x6b,
	0x69, 0x6e, 0x64, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f,
	0x6e, 0x75, 0x6d, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6b, 0x69, 0x6e, 0x64, 0x42, 0x0a, 0x0a, 0x08,
	0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x4e, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x73, 0x65, 0x5f, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x73,
	0x65, 0x2e, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x0a, 0x70, 0x72,
	0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x29, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x34, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f,
	0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x40, 0x0a, 0x1f, 0x4c, 0x69, 0x73,
	0x74, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x42, 0x79, 0x43, 0x68,
	0x61, 0x70, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x49, 0x64, 0x22, 0x79, 0x0a, 0x20, 0x4c,
	0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x42, 0x79,
	0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x34, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x73, 0x65, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x73, 0x65, 0x2e, 0x50, 0x72,
	0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x73, 0x65, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x86, 0x01, 0x0a, 0x20, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x70,
	0x72, 0x6f, 0x73, 0x65, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49,
	0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x22,
	0x5d, 0x0a, 0x21, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x73, 0x65, 0x2e,
	0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x52, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x22, 0x53,
	0x0a, 0x2b, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x42, 0x79, 0x50, 0x72, 0x6f, 0x73,
	0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a,
	0x0e, 0x70, 0x72, 0x6f, 0x73, 0x65, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x49, 0x64, 0x22, 0x8b, 0x01, 0x0a, 0x2c, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x73,
	0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73,
	0x42, 0x79, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x0a, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x73, 0x65,
	0x2e, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x52, 0x0a, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73,
	0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x5e, 0x0a, 0x1e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x73, 0x42, 0x79, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49,
	0x64, 0x22, 0x78, 0x0a, 0x1f, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x73, 0x42, 0x79, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x73, 0x65, 0x5f, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f,
	0x73, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x0b, 0x70,
	0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x32, 0x0a, 0x20, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x3d, 0x0a, 0x21, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0xcb,
	0x03, 0x0a, 0x11, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x53, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72,
	0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x73, 0x65,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x73, 0x65,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f,
	0x73, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x73, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50,
	0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x73,
	0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x73,
	0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x10, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x1e,
	0x2e, 0x70, 0x72, 0x6f, 0x73, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f,
	0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f,
	0x2e, 0x70, 0x72, 0x6f, 0x73, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f,
	0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x6b, 0x0a, 0x18, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x73, 0x42, 0x79, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x12, 0x26, 0x2e, 0x70, 0x72,
	0x6f, 0x73, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x73, 0x42, 0x79, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x70, 0x72, 0x6f, 0x73, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x42, 0x79, 0x43, 0x68, 0x61,
	0x70, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xf8, 0x03, 0x0a,
	0x1a, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6e, 0x0a, 0x19, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x27, 0x2e, 0x70, 0x72, 0x6f, 0x73, 0x65,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x73, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x8f, 0x01, 0x0a, 0x24,
	0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x42, 0x79, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x73, 0x65, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x73, 0x42, 0x79, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x33, 0x2e, 0x70, 0x72, 0x6f, 0x73, 0x65,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x42, 0x79, 0x50, 0x72, 0x6f, 0x73, 0x65,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x68, 0x0a,
	0x17, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73,
	0x42, 0x79, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x73, 0x65,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73,
	0x42, 0x79, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x26, 0x2e, 0x70, 0x72, 0x6f, 0x73, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x73,
	0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x42, 0x79, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6e, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x12, 0x27, 0x2e, 0x70, 0x72, 0x6f, 0x73, 0x65, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e,
	0x70, 0x72, 0x6f, 0x73, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x73,
	0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2d, 0x65, 0x6e, 0x67, 0x69,
	0x6e, 0x65, 0x2f, 0x6d, 0x61, 0x69, 0x6e, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_prose_prose_proto_rawDescOnce sync.Once
	file_proto_prose_prose_proto_rawDescData = file_proto_prose_prose_proto_rawDesc
)

func file_proto_prose_prose_proto_rawDescGZIP() []byte {
	file_proto_prose_prose_proto_rawDescOnce.Do(func() {
		file_proto_prose_prose_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_prose_prose_proto_rawDescData)
	})
	return file_proto_prose_prose_proto_rawDescData
}

var file_proto_prose_prose_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_prose_prose_proto_goTypes = []interface{}{
	(*ProseBlock)(nil),                                   // 0: prose.ProseBlock
	(*ProseBlockReference)(nil),                          // 1: prose.ProseBlockReference
	(*CreateProseBlockRequest)(nil),                      // 2: prose.CreateProseBlockRequest
	(*CreateProseBlockResponse)(nil),                     // 3: prose.CreateProseBlockResponse
	(*GetProseBlockRequest)(nil),                         // 4: prose.GetProseBlockRequest
	(*GetProseBlockResponse)(nil),                        // 5: prose.GetProseBlockResponse
	(*UpdateProseBlockRequest)(nil),                      // 6: prose.UpdateProseBlockRequest
	(*UpdateProseBlockResponse)(nil),                     // 7: prose.UpdateProseBlockResponse
	(*DeleteProseBlockRequest)(nil),                      // 8: prose.DeleteProseBlockRequest
	(*DeleteProseBlockResponse)(nil),                     // 9: prose.DeleteProseBlockResponse
	(*ListProseBlocksByChapterRequest)(nil),              // 10: prose.ListProseBlocksByChapterRequest
	(*ListProseBlocksByChapterResponse)(nil),             // 11: prose.ListProseBlocksByChapterResponse
	(*CreateProseBlockReferenceRequest)(nil),             // 12: prose.CreateProseBlockReferenceRequest
	(*CreateProseBlockReferenceResponse)(nil),            // 13: prose.CreateProseBlockReferenceResponse
	(*ListProseBlockReferencesByProseBlockRequest)(nil),  // 14: prose.ListProseBlockReferencesByProseBlockRequest
	(*ListProseBlockReferencesByProseBlockResponse)(nil), // 15: prose.ListProseBlockReferencesByProseBlockResponse
	(*ListProseBlocksByEntityRequest)(nil),               // 16: prose.ListProseBlocksByEntityRequest
	(*ListProseBlocksByEntityResponse)(nil),              // 17: prose.ListProseBlocksByEntityResponse
	(*DeleteProseBlockReferenceRequest)(nil),             // 18: prose.DeleteProseBlockReferenceRequest
	(*DeleteProseBlockReferenceResponse)(nil),            // 19: prose.DeleteProseBlockReferenceResponse
	(*timestamppb.Timestamp)(nil),                        // 20: google.protobuf.Timestamp
}
var file_proto_prose_prose_proto_depIdxs = []int32{
	20, // 0: prose.ProseBlock.created_at:type_name -> google.protobuf.Timestamp
	20, // 1: prose.ProseBlock.updated_at:type_name -> google.protobuf.Timestamp
	20, // 2: prose.ProseBlockReference.created_at:type_name -> google.protobuf.Timestamp
	0,  // 3: prose.CreateProseBlockResponse.prose_block:type_name -> prose.ProseBlock
	0,  // 4: prose.GetProseBlockResponse.prose_block:type_name -> prose.ProseBlock
	0,  // 5: prose.UpdateProseBlockResponse.prose_block:type_name -> prose.ProseBlock
	0,  // 6: prose.ListProseBlocksByChapterResponse.prose_blocks:type_name -> prose.ProseBlock
	1,  // 7: prose.CreateProseBlockReferenceResponse.reference:type_name -> prose.ProseBlockReference
	1,  // 8: prose.ListProseBlockReferencesByProseBlockResponse.references:type_name -> prose.ProseBlockReference
	0,  // 9: prose.ListProseBlocksByEntityResponse.prose_blocks:type_name -> prose.ProseBlock
	2,  // 10: prose.ProseBlockService.CreateProseBlock:input_type -> prose.CreateProseBlockRequest
	4,  // 11: prose.ProseBlockService.GetProseBlock:input_type -> prose.GetProseBlockRequest
	6,  // 12: prose.ProseBlockService.UpdateProseBlock:input_type -> prose.UpdateProseBlockRequest
	8,  // 13: prose.ProseBlockService.DeleteProseBlock:input_type -> prose.DeleteProseBlockRequest
	10, // 14: prose.ProseBlockService.ListProseBlocksByChapter:input_type -> prose.ListProseBlocksByChapterRequest
	12, // 15: prose.ProseBlockReferenceService.CreateProseBlockReference:input_type -> prose.CreateProseBlockReferenceRequest
	14, // 16: prose.ProseBlockReferenceService.ListProseBlockReferencesByProseBlock:input_type -> prose.ListProseBlockReferencesByProseBlockRequest
	16, // 17: prose.ProseBlockReferenceService.ListProseBlocksByEntity:input_type -> prose.ListProseBlocksByEntityRequest
	18, // 18: prose.ProseBlockReferenceService.DeleteProseBlockReference:input_type -> prose.DeleteProseBlockReferenceRequest
	3,  // 19: prose.ProseBlockService.CreateProseBlock:output_type -> prose.CreateProseBlockResponse
	5,  // 20: prose.ProseBlockService.GetProseBlock:output_type -> prose.GetProseBlockResponse
	7,  // 21: prose.ProseBlockService.UpdateProseBlock:output_type -> prose.UpdateProseBlockResponse
	9,  // 22: prose.ProseBlockService.DeleteProseBlock:output_type -> prose.DeleteProseBlockResponse
	11, // 23: prose.ProseBlockService.ListProseBlocksByChapter:output_type -> prose.ListProseBlocksByChapterResponse
	13, // 24: prose.ProseBlockReferenceService.CreateProseBlockReference:output_type -> prose.CreateProseBlockReferenceResponse
	15, // 25: prose.ProseBlockReferenceService.ListProseBlockReferencesByProseBlock:output_type -> prose.ListProseBlockReferencesByProseBlockResponse
	17, // 26: prose.ProseBlockReferenceService.ListProseBlocksByEntity:output_type -> prose.ListProseBlocksByEntityResponse
	19, // 27: prose.ProseBlockReferenceService.DeleteProseBlockReference:output_type -> prose.DeleteProseBlockReferenceResponse
	19, // [19:28] is the sub-list for method output_type
	10, // [10:19] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_prose_prose_proto_init() }
func file_proto_prose_prose_proto_init() {
	if File_proto_prose_prose_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_prose_prose_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProseBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_prose_prose_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProseBlockReference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_prose_prose_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateProseBlockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_prose_prose_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateProseBlockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_prose_prose_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProseBlockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_prose_prose_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProseBlockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_prose_prose_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateProseBlockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_prose_prose_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateProseBlockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_prose_prose_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteProseBlockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_prose_prose_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteProseBlockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_prose_prose_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListProseBlocksByChapterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_prose_prose_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListProseBlocksByChapterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_prose_prose_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateProseBlockReferenceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_prose_prose_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateProseBlockReferenceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_prose_prose_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListProseBlockReferencesByProseBlockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_prose_prose_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListProseBlockReferencesByProseBlockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_prose_prose_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListProseBlocksByEntityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_prose_prose_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListProseBlocksByEntityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_prose_prose_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteProseBlockReferenceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_prose_prose_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteProseBlockReferenceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_prose_prose_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_proto_prose_prose_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_proto_prose_prose_proto_msgTypes[6].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_prose_prose_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_prose_prose_proto_goTypes,
		DependencyIndexes: file_proto_prose_prose_proto_depIdxs,
		MessageInfos:      file_proto_prose_prose_proto_msgTypes,
	}.Build()
	File_proto_prose_prose_proto = out.File
	file_proto_prose_prose_proto_rawDesc = nil
	file_proto_prose_prose_proto_goTypes = nil
	file_proto_prose_prose_proto_depIdxs = nil
}
