// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.2
// source: proto/trait/trait.proto

package trait

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TraitService_CreateTrait_FullMethodName = "/trait.TraitService/CreateTrait"
	TraitService_GetTrait_FullMethodName    = "/trait.TraitService/GetTrait"
	TraitService_UpdateTrait_FullMethodName = "/trait.TraitService/UpdateTrait"
	TraitService_ListTraits_FullMethodName  = "/trait.TraitService/ListTraits"
	TraitService_DeleteTrait_FullMethodName = "/trait.TraitService/DeleteTrait"
)

// TraitServiceClient is the client API for TraitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TraitServiceClient interface {
	CreateTrait(ctx context.Context, in *CreateTraitRequest, opts ...grpc.CallOption) (*CreateTraitResponse, error)
	GetTrait(ctx context.Context, in *GetTraitRequest, opts ...grpc.CallOption) (*GetTraitResponse, error)
	UpdateTrait(ctx context.Context, in *UpdateTraitRequest, opts ...grpc.CallOption) (*UpdateTraitResponse, error)
	ListTraits(ctx context.Context, in *ListTraitsRequest, opts ...grpc.CallOption) (*ListTraitsResponse, error)
	DeleteTrait(ctx context.Context, in *DeleteTraitRequest, opts ...grpc.CallOption) (*DeleteTraitResponse, error)
}

type traitServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTraitServiceClient(cc grpc.ClientConnInterface) TraitServiceClient {
	return &traitServiceClient{cc}
}

func (c *traitServiceClient) CreateTrait(ctx context.Context, in *CreateTraitRequest, opts ...grpc.CallOption) (*CreateTraitResponse, error) {
	out := new(CreateTraitResponse)
	err := c.cc.Invoke(ctx, TraitService_CreateTrait_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traitServiceClient) GetTrait(ctx context.Context, in *GetTraitRequest, opts ...grpc.CallOption) (*GetTraitResponse, error) {
	out := new(GetTraitResponse)
	err := c.cc.Invoke(ctx, TraitService_GetTrait_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traitServiceClient) UpdateTrait(ctx context.Context, in *UpdateTraitRequest, opts ...grpc.CallOption) (*UpdateTraitResponse, error) {
	out := new(UpdateTraitResponse)
	err := c.cc.Invoke(ctx, TraitService_UpdateTrait_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traitServiceClient) ListTraits(ctx context.Context, in *ListTraitsRequest, opts ...grpc.CallOption) (*ListTraitsResponse, error) {
	out := new(ListTraitsResponse)
	err := c.cc.Invoke(ctx, TraitService_ListTraits_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traitServiceClient) DeleteTrait(ctx context.Context, in *DeleteTraitRequest, opts ...grpc.CallOption) (*DeleteTraitResponse, error) {
	out := new(DeleteTraitResponse)
	err := c.cc.Invoke(ctx, TraitService_DeleteTrait_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TraitServiceServer is the server API for TraitService service.
// All implementations must embed UnimplementedTraitServiceServer
// for forward compatibility
type TraitServiceServer interface {
	CreateTrait(context.Context, *CreateTraitRequest) (*CreateTraitResponse, error)
	GetTrait(context.Context, *GetTraitRequest) (*GetTraitResponse, error)
	UpdateTrait(context.Context, *UpdateTraitRequest) (*UpdateTraitResponse, error)
	ListTraits(context.Context, *ListTraitsRequest) (*ListTraitsResponse, error)
	DeleteTrait(context.Context, *DeleteTraitRequest) (*DeleteTraitResponse, error)
	mustEmbedUnimplementedTraitServiceServer()
}

// UnimplementedTraitServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTraitServiceServer struct {
}

func (UnimplementedTraitServiceServer) CreateTrait(context.Context, *CreateTraitRequest) (*CreateTraitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTrait not implemented")
}
func (UnimplementedTraitServiceServer) GetTrait(context.Context, *GetTraitRequest) (*GetTraitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrait not implemented")
}
func (UnimplementedTraitServiceServer) UpdateTrait(context.Context, *UpdateTraitRequest) (*UpdateTraitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTrait not implemented")
}
func (UnimplementedTraitServiceServer) ListTraits(context.Context, *ListTraitsRequest) (*ListTraitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTraits not implemented")
}
func (UnimplementedTraitServiceServer) DeleteTrait(context.Context, *DeleteTraitRequest) (*DeleteTraitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTrait not implemented")
}
func (UnimplementedTraitServiceServer) mustEmbedUnimplementedTraitServiceServer() {}

// UnsafeTraitServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TraitServiceServer will
// result in compilation errors.
type UnsafeTraitServiceServer interface {
	mustEmbedUnimplementedTraitServiceServer()
}

func RegisterTraitServiceServer(s grpc.ServiceRegistrar, srv TraitServiceServer) {
	s.RegisterService(&TraitService_ServiceDesc, srv)
}

func _TraitService_CreateTrait_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTraitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraitServiceServer).CreateTrait(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TraitService_CreateTrait_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraitServiceServer).CreateTrait(ctx, req.(*CreateTraitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TraitService_GetTrait_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTraitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraitServiceServer).GetTrait(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TraitService_GetTrait_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraitServiceServer).GetTrait(ctx, req.(*GetTraitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TraitService_UpdateTrait_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTraitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraitServiceServer).UpdateTrait(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TraitService_UpdateTrait_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraitServiceServer).UpdateTrait(ctx, req.(*UpdateTraitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TraitService_ListTraits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTraitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraitServiceServer).ListTraits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TraitService_ListTraits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraitServiceServer).ListTraits(ctx, req.(*ListTraitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TraitService_DeleteTrait_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTraitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraitServiceServer).DeleteTrait(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TraitService_DeleteTrait_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraitServiceServer).DeleteTrait(ctx, req.(*DeleteTraitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TraitService_ServiceDesc is the grpc.ServiceDesc for TraitService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TraitService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trait.TraitService",
	HandlerType: (*TraitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTrait",
			Handler:    _TraitService_CreateTrait_Handler,
		},
		{
			MethodName: "GetTrait",
			Handler:    _TraitService_GetTrait_Handler,
		},
		{
			MethodName: "UpdateTrait",
			Handler:    _TraitService_UpdateTrait_Handler,
		},
		{
			MethodName: "ListTraits",
			Handler:    _TraitService_ListTraits_Handler,
		},
		{
			MethodName: "DeleteTrait",
			Handler:    _TraitService_DeleteTrait_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/trait/trait.proto",
}
